import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderRadius: 26,
    paddingTop: 18,
    overflow: "hidden",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 12,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  authorName: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginTop: 1,
  },
  metaText: {
    fontSize: 12,
    lineHeight: 17,
  },
  optionsButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    padding: 0,
    marginTop: 16,
    paddingHorizontal: 18,
    fontSize: 22,
    lineHeight: 28,
  },
  description: {
    paddingHorizontal: 18,
    marginTop: 5,
    fontSize: 14,
    lineHeight: 22,
  },
  descriptionWithoutTitle: {
    marginTop: 16,
  },
  statsPanel: {
    flexDirection: "row",
    marginHorizontal: 18,
    marginTop: 18,
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  statItem: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minWidth: 0,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
    lineHeight: 13,
    marginBottom: 5,
  },
  statValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  statValue: {
    fontSize: 23,
    fontWeight: "900",
    lineHeight: 27,
  },
  statUnit: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    lineHeight: 19,
  },
  topSetsTitle: {
    marginHorizontal: 18,
    marginTop: 14,
    marginBottom: 7,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.6,
    textTransform: "uppercase",
    lineHeight: 14,
  },
  topSetsPanel: {
    marginHorizontal: 18,
    marginTop: 0,
    borderWidth: 1,
    borderRadius: 16,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 0,
    overflow: "hidden",
  },
  topSetTableHeader: {
    flexDirection: "row",
    minHeight: 30,
    borderBottomWidth: 1,
  },
  topSetTableRow: {
    flexDirection: "row",
    minHeight: 46,
    borderBottomWidth: 1,
  },
  topSetLastRow: {
    borderBottomWidth: 0,
  },
  topSetHeaderCell: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 3,
  },
  topSetExerciseHeaderCell: {
    alignItems: "flex-start",
    paddingLeft: 8,
  },
  topSetHeaderText: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    lineHeight: 12,
  },
  topSetCell: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 3,
  },
  topSetExerciseCell: {
    flex: 30,
    minWidth: 0,
  },
  topSetMetricCell: {
    flex: 14,
    minWidth: 0,
  },
  topSetExerciseText: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  topSetExerciseContent: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingLeft: 5,
    minWidth: 0,
  },
  topSetValueText: {
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 16,
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 26,
    marginTop: 18,
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderTopWidth: 1,
  },
  footerAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  footerText: {
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
  },
});
