import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderRadius: 26,
    paddingTop: 18,
    overflow: "hidden",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 12,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  authorName: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginTop: 1,
  },
  metaText: {
    fontSize: 12,
    lineHeight: 17,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    opacity: 0.8,
  },
  workoutType: {
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  categoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginTop: 15,
    paddingHorizontal: 18,
  },
  categoryLabel: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 2.4,
    textTransform: "uppercase",
    lineHeight: 16,
  },
  title: {
    padding: 0,
    marginTop: 7,
    paddingHorizontal: 18,
    fontSize: 22,
    lineHeight: 28,
  },
  description: {
    paddingHorizontal: 18,
    marginTop: 5,
    fontSize: 14,
    lineHeight: 22,
  },
  statsPanel: {
    flexDirection: "row",
    marginHorizontal: 18,
    marginTop: 18,
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  statItem: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minWidth: 0,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
    lineHeight: 13,
    marginBottom: 5,
  },
  statValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 4,
  },
  statValue: {
    fontSize: 23,
    fontWeight: "900",
    lineHeight: 27,
  },
  statUnit: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    lineHeight: 19,
  },
  volumePanel: {
    marginHorizontal: 18,
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  panelLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  panelLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2.2,
    textTransform: "uppercase",
    lineHeight: 14,
  },
  volumeValueRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 5,
  },
  volumeValue: {
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 28,
  },
  volumeUnit: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    lineHeight: 20,
  },
  prPanel: {
    marginHorizontal: 18,
    marginTop: 12,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  prHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  prHeaderText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 2,
    textTransform: "uppercase",
    lineHeight: 14,
  },
  prRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 9,
  },
  prExercise: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 18,
  },
  prResult: {
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 18,
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 26,
    marginTop: 18,
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderTopWidth: 1,
  },
  footerAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  footerText: {
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 18,
  },
  footerSpacer: {
    flex: 1,
  },
});
