import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  toolbar: {
    paddingTop: 12,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toolbarIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  toolbarPill: {
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 1,
  },
  pillChevron: {
    transform: [{ rotate: "90deg" }],
  },
  toolbarPillText: {
    fontSize: 12,
    fontWeight: "700",
  },
  resultCount: {
    marginLeft: "auto",
    fontSize: 12,
    fontWeight: "700",
  },
  optionSheetTitle: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    paddingHorizontal: 6,
    paddingBottom: 8,
  },
  optionSheetRow: {
    height: 46,
    borderRadius: 10,
    paddingHorizontal: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  optionSheetLabel: {
    fontSize: 13,
    fontWeight: "700",
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    gap: 10,
  },
  stateBlock: {
    paddingVertical: 32,
    alignItems: "center",
    gap: 14,
  },
  stateText: {
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  stateAction: {
    minHeight: 44,
    minWidth: 140,
    borderRadius: 22,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  stateActionText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "900",
  },
  row: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  comingSoonRow: {
    opacity: 0.55,
  },
  rowTop: {
    minHeight: 88,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  rowMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  iconTile: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  rowCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  rowTitle: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  rowMeta: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "600",
  },
  rowChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 2,
  },
  rowChip: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  rowChipText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "700",
  },
  favoriteButton: {
    width: 40,
    height: 40,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  actionsRow: {
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingVertical: 10,
  },
  actionButton: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: "800",
  },
  exerciseList: {
    borderTopWidth: 1,
    paddingVertical: 10,
    gap: 6,
  },
  exerciseRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  exerciseName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "600",
  },
  exerciseDetail: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
  },
});
