import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 18,
  },
  pageHeaderTitleGroup: {
    alignItems: "center",
    justifyContent: "center",
  },
  pageHeaderTitleEyebrow: {
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  pageHeaderTitleMain: {
    textAlign: "center",
    lineHeight: 26,
  },
  exerciseList: {
    gap: 10,
  },
  exerciseListItem: {
    minHeight: 78,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  exerciseListIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  exerciseListText: {
    flex: 1,
    minWidth: 0,
  },
  exerciseListTitle: {
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 21,
  },
  exerciseListMeta: {
    fontSize: 12,
    lineHeight: 16,
    marginTop: 3,
  },
  exerciseListStats: {
    minWidth: 42,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  exerciseListStatValue: {
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 22,
  },
  exerciseListStatLabel: {
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
    textTransform: "uppercase",
  },
  loadingState: {
    minHeight: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
  },
  emptyStateTitle: {
    fontSize: 17,
    fontWeight: "800",
    lineHeight: 22,
  },
  emptyStateText: {
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
  },
  recordToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  backToListButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  backToListText: {
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 16,
  },
  recordFilterButton: {
    maxWidth: 116,
    minHeight: 34,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  recordFilterText: {
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 16,
  },
  recordCard: {
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  recordCardAccent: {
    height: 3,
  },
  recordCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  recordIconTile: {
    width: 50,
    height: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  recordHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  recordEyebrow: {
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 13,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  recordTitle: {
    lineHeight: 27,
  },
  tableHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  tableHeaderText: {
    width: 58,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    textTransform: "uppercase",
  },
  tableHeaderWeight: {
    flex: 1,
    width: "auto",
  },
  tableHeaderDate: {
    width: 96,
    textAlign: "right",
  },
  recordRow: {
    minHeight: 74,
    borderTopWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    position: "relative",
  },
  recordRowAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
  },
  repsBadge: {
    width: 35,
    height: 35,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 24,
  },
  repsBadgeText: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 18,
  },
  recordWeightCell: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  recordWeightLine: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  recordWeightValue: {
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 23,
  },
  mutedRecordValue: {
    opacity: 0.65,
  },
  recordWeightUnit: {
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    marginLeft: 6,
    textTransform: "uppercase",
  },
  gainBadge: {
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginLeft: 10,
  },
  gainBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 12,
  },
  newBadge: {
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginLeft: 8,
  },
  newBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 12,
  },
  progressTrack: {
    height: 5,
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 7,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  recordDateCell: {
    width: 98,
    alignItems: "flex-end",
  },
  recordDateLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
  },
  recordDateText: {
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 17,
    textAlign: "right",
  },
  recordRelativeDate: {
    fontSize: 11,
    lineHeight: 14,
    marginTop: 2,
    textAlign: "right",
  },
});
