import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 18,
  },
  pageHeaderTitleGroup: {
    alignItems: "center",
    justifyContent: "center",
  },
  pageHeaderTitleEyebrow: {
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  pageHeaderTitleMain: {
    textAlign: "center",
    lineHeight: 26,
  },
  muscleLoadCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
  },
  muscleLoadHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  muscleLoadHeaderText: {
    flex: 1,
    minWidth: 150,
  },
  muscleLoadEyebrow: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  muscleLoadTitle: {
    fontSize: 19,
    fontWeight: "900",
    lineHeight: 24,
  },
  muscleLoadPicker: {
    minWidth: 132,
    maxWidth: 170,
    minHeight: 38,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  muscleLoadChartFrame: {
    minHeight: 300,
    borderRadius: 10,
    overflow: "hidden",
    marginTop: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  muscleLoadEmptyState: {
    minHeight: 300,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  muscleLoadEmptyTitle: {
    fontSize: 19,
    fontWeight: "900",
    lineHeight: 24,
    textAlign: "center",
  },
  muscleLoadEmptyText: {
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
    marginTop: 5,
  },
  exerciseList: {
    gap: 10,
  },
  exerciseListItem: {
    minHeight: 78,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  exerciseListIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  exerciseListText: {
    flex: 1,
    minWidth: 0,
  },
  exerciseListTitle: {
    fontSize: 19,
    fontWeight: "800",
    lineHeight: 24,
  },
  exerciseListMeta: {
    fontSize: 15,
    lineHeight: 20,
    marginTop: 3,
  },
  exerciseListStats: {
    minWidth: 42,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  exerciseListStatValue: {
    fontSize: 19,
    fontWeight: "800",
    lineHeight: 24,
  },
  exerciseListStatLabel: {
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 15,
    textTransform: "uppercase",
  },
  loadingState: {
    minHeight: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
  },
  emptyStateTitle: {
    fontSize: 19,
    fontWeight: "800",
    lineHeight: 24,
  },
  emptyStateText: {
    fontSize: 15,
    lineHeight: 20,
    marginTop: 6,
  },
  recordToolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 12,
  },
  backToListButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  backToListText: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  recordFilterToggle: {
    flexGrow: 1,
    minWidth: 210,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
  },
  recordFilterLabel: {
    flexShrink: 1,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
    textAlign: "right",
  },
  recordCard: {
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  recordCardAccent: {
    height: 3,
  },
  recordCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  recordIconTile: {
    width: 50,
    height: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  recordHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  recordEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 15,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  recordTitle: {
    lineHeight: 27,
  },
  tableHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  tableHeaderText: {
    width: 58,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 15,
    textTransform: "uppercase",
  },
  tableHeaderWeight: {
    flex: 1,
    width: "auto",
  },
  tableHeaderDate: {
    width: 96,
    textAlign: "right",
  },
  recordRow: {
    minHeight: 74,
    borderTopWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    position: "relative",
  },
  recordRowAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
  },
  repsBadge: {
    width: 35,
    height: 35,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  repsBadgeText: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
  },
  recordWeightCell: {
    flex: 1,
    minWidth: 0,
    paddingRight: 12,
  },
  recordWeightLine: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  recordWeightValue: {
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 31,
  },
  mutedRecordValue: {
    opacity: 0.65,
  },
  recordWeightUnit: {
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 15,
    marginLeft: 6,
    textTransform: "uppercase",
  },
  gainBadge: {
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginLeft: 10,
  },
  gainBadgeText: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
  },
  newBadge: {
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginLeft: 8,
  },
  newBadgeText: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
  },
  progressTrack: {
    height: 5,
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 7,
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  recordDateCell: {
    width: 98,
    alignItems: "flex-end",
  },
  recordDateLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 5,
  },
  recordDateText: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
    textAlign: "right",
  },
  tableFootnote: {
    borderTopWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 14,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 15,
  },
  recordRelativeDate: {
    fontSize: 12,
    lineHeight: 15,
    marginTop: 2,
    textAlign: "right",
  },
  trendCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
    marginTop: 14,
  },
  trendHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  trendHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  trendEyebrow: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  trendTitle: {
    fontSize: 19,
    fontWeight: "900",
    lineHeight: 24,
  },
  trendCountPill: {
    minWidth: 76,
    minHeight: 42,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  trendCountValue: {
    fontSize: 19,
    fontWeight: "900",
    lineHeight: 24,
  },
  trendCountLabel: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
    textTransform: "uppercase",
  },
  trendMetrics: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  trendMetric: {
    flex: 1,
    minWidth: 0,
  },
  trendMetricLabel: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  trendMetricValue: {
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 31,
  },
  trendMetricSubvalue: {
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 2,
  },
  trendChartFrame: {
    minHeight: 190,
    borderWidth: 1,
    borderRadius: 14,
    overflow: "hidden",
    marginTop: 16,
  },
  trendEmptyState: {
    minHeight: 190,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  trendEmptyTitle: {
    fontSize: 19,
    fontWeight: "900",
    lineHeight: 24,
    textAlign: "center",
  },
  trendEmptyText: {
    fontSize: 15,
    lineHeight: 20,
    textAlign: "center",
    marginTop: 5,
  },
  trendFooter: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
  },
  trendFooterLabel: {
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
    textTransform: "uppercase",
  },
  trendFooterValue: {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
    textAlign: "right",
  },
});
