import { StyleSheet } from 'react-native';
import { Radius, Spacing } from '@resources/GlobalStyling/spacing';

export default StyleSheet.create({
  container: { flex: 1 },
  content: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg, paddingBottom: Spacing.xxl, gap: Spacing.md },
  header: { gap: Spacing.lg },
  search: { minHeight: 48, borderWidth: 1, borderRadius: Radius.md, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
  input: { flex: 1, minHeight: 46, fontSize: 15, paddingVertical: 0 },
  iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  panel: { padding: Spacing.lg, gap: Spacing.md },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  grow: { flex: 1 },
  label: { fontSize: 12, fontWeight: '800', letterSpacing: 1.2 },
  title: { fontSize: 22, fontWeight: '800', lineHeight: 28, letterSpacing: -0.3 },
  smallButton: { minHeight: 44, paddingHorizontal: 12, borderWidth: 1, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' },
  bodies: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', gap: 12 },
  figure: { alignItems: 'center', gap: 8 },
  figureLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 1.2 },
  bodyFrame: { overflow: 'hidden', position: 'relative' },
  hint: { textAlign: 'center', fontSize: 12, lineHeight: 18 },
  legend: { flexDirection: 'row', gap: 14, flexWrap: 'wrap', paddingTop: 12, borderTopWidth: 1 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  dot: { width: 9, height: 9, borderRadius: 3 },
  roleRow: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, paddingVertical: 10 },
  roleName: { fontSize: 14, fontWeight: '600', lineHeight: 20 },
  note: { fontSize: 12, lineHeight: 18 },
  chip: { minHeight: 44, borderWidth: 1, borderRadius: Radius.sm, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', gap: 8, alignItems: 'center' },
  listHeading: { fontSize: 15, fontWeight: '700', paddingVertical: 4 },
  exerciseRow: { minHeight: 72, borderWidth: 1, borderRadius: Radius.lg, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 },
  exerciseIcon: { width: 40, height: 40, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' },
  exerciseName: { fontSize: 14, fontWeight: '700', lineHeight: 20 },
  exerciseMeta: { fontSize: 12, lineHeight: 18, marginTop: 3 },
  spacer: { height: 8 },
});
