import { StyleSheet } from "react-native";

// Layout only. Colours are read from `theme` in the component body:
// applyAccentTheme() mutates Colors at runtime, and StyleSheet.create runs once.
export default StyleSheet.create({
  container: { flex: 1 },
  list: { flex: 1 },
  listContent: { paddingBottom: 28 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingTop: 12,
    paddingHorizontal: 20,
  },
  back: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCopy: { flex: 1, minWidth: 0, gap: 2 },
  eyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1.8, textTransform: "uppercase" },
  title: { fontSize: 23, fontWeight: "800", letterSpacing: -0.5, lineHeight: 27 },

  // Search
  search: {
    marginTop: 14,
    marginHorizontal: 20,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    paddingLeft: 14,
    paddingRight: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInput: { flex: 1, minWidth: 0, height: "100%", fontSize: 13.5, fontWeight: "600", paddingVertical: 0 },
  searchClear: { width: 36, height: 36, alignItems: "center", justifyContent: "center" },

  // Sort and filter
  controls: { marginTop: 12, marginHorizontal: 20, flexDirection: "row", gap: 9 },
  sortButton: {
    flex: 1,
    minWidth: 0,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  sortEyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 0.8, textTransform: "uppercase" },
  sortValue: { flex: 1, minWidth: 0, fontSize: 12.5, fontWeight: "800" },
  filterButton: {
    height: 36,
    maxWidth: 148,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  filterLabel: { flexShrink: 1, fontSize: 12.5, fontWeight: "800" },

  // The sorts, as chips
  chipsScroll: { marginTop: 12, flexGrow: 0 },
  chips: { paddingHorizontal: 20, gap: 7 },
  chip: {
    height: 30,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  chipText: { fontSize: 12, fontWeight: "800" },

  // "Choose your centre", under the "In your centre" sort
  hint: {
    marginTop: 12,
    marginHorizontal: 20,
    borderRadius: 16,
    borderWidth: 1,
    paddingVertical: 11,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  hintIcon: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  hintCopy: { flex: 1, minWidth: 0, gap: 1 },
  hintTitle: { fontSize: 13, fontWeight: "800", lineHeight: 17 },
  hintBody: { fontSize: 11, fontWeight: "600", lineHeight: 15 },

  // Result line
  result: {
    marginTop: 14,
    marginHorizontal: 20,
    marginBottom: 10,
    minHeight: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  resultCount: { flex: 1, minWidth: 0, fontSize: 10.5, fontWeight: "700", lineHeight: 14 },
  resultReset: { fontSize: 10.5, fontWeight: "700", lineHeight: 14 },

  // Rows
  row: { marginHorizontal: 20, marginBottom: 9 },
  skeleton: { marginTop: 14 },

  // Nothing shared yet
  hero: {
    marginTop: 18,
    marginHorizontal: 20,
    borderRadius: 22,
    borderWidth: 1,
    paddingTop: 26,
    paddingHorizontal: 22,
    paddingBottom: 20,
    alignItems: "center",
  },
  // Three cards fanned out: the tile, and the two exercises either side of
  // it that are not there yet.
  heroArt: { width: 176, height: 92, alignItems: "center", justifyContent: "center" },
  heroGhost: {
    position: "absolute",
    top: 16,
    width: 54,
    height: 64,
    borderRadius: 14,
    borderWidth: 1,
    padding: 7,
    gap: 5,
  },
  heroGhostLeft: { left: 14, transform: [{ rotate: "-9deg" }] },
  heroGhostRight: { right: 14, transform: [{ rotate: "9deg" }] },
  heroGhostMedia: { height: 24, borderRadius: 6 },
  heroGhostLine: { height: 5, borderRadius: 3 },
  heroGhostLineShort: { width: "60%", height: 5, borderRadius: 3 },
  heroTile: { width: 76, height: 76, borderRadius: 24, overflow: "hidden" },
  heroTileInner: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: {
    marginTop: 16,
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: -0.3,
    lineHeight: 24,
    textAlign: "center",
  },
  heroBody: {
    marginTop: 8,
    maxWidth: 300,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 19,
    textAlign: "center",
  },
  heroCta: {
    marginTop: 20,
    alignSelf: "stretch",
    minHeight: 48,
    borderRadius: 15,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  heroCtaText: { fontSize: 14, fontWeight: "800" },
  heroNote: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 6,
    maxWidth: 300,
  },
  heroNoteIcon: { marginTop: 1 },
  heroNoteText: { flexShrink: 1, fontSize: 10.5, fontWeight: "700", lineHeight: 15, textAlign: "center" },

  // No results, nothing saved and the like
  empty: {
    marginTop: 14,
    marginHorizontal: 20,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 22,
    paddingHorizontal: 20,
    alignItems: "center",
    gap: 8,
  },
  emptyIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  emptyTitle: { fontSize: 15.5, fontWeight: "800", lineHeight: 20, textAlign: "center" },
  emptyBody: { maxWidth: 290, fontSize: 12.5, fontWeight: "600", lineHeight: 18, textAlign: "center" },
  emptyAction: {
    marginTop: 6,
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyActionText: { fontSize: 13, fontWeight: "800" },

  // Footer
  footerSpinner: { paddingVertical: 18 },
  moreFailed: {
    marginHorizontal: 20,
    marginTop: 4,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  moreFailedText: { flexShrink: 1, fontSize: 12, fontWeight: "700", lineHeight: 16 },
  moreRetry: { minHeight: 32, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, justifyContent: "center" },
  moreRetryText: { fontSize: 12, fontWeight: "800" },
  invite: {
    marginTop: 6,
    marginHorizontal: 20,
    borderRadius: 18,
    borderWidth: 1,
    borderStyle: "dashed",
    paddingVertical: 14,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  inviteIcon: { width: 36, height: 36, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  inviteCopy: { flex: 1, minWidth: 0, gap: 2 },
  inviteTitle: { fontSize: 13.5, fontWeight: "800", lineHeight: 18 },
  inviteAction: { fontSize: 12, fontWeight: "800", lineHeight: 16 },
});
