import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  quickAccessSection: {
    marginBottom: 18,
  },
  quickAccessGrid: {
    gap: 12,
  },
  quickAccessCard: {
    borderWidth: 1,
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 16,
    overflow: "hidden",
  },
  quickAccessAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 4,
  },
  quickAccessCardHeader: {
    marginBottom: 10,
  },
  quickAccessCardEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  quickAccessCardTitle: {
    lineHeight: 28,
  },
  quickAccessCardDescription: {
    fontSize: 14,
    lineHeight: 21,
  },
  quickAccessMetricsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  quickAccessMetricCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 8,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 74,
  },
  quickAccessMetricValue: {
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 28,
  },
  quickAccessMetricLabel: {
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
    textTransform: "uppercase",
    marginTop: 4,
    textAlign: "center",
  },
  heroMetricCardCentered: {
    alignItems: "center",
  },
  heroMetricTextCentered: {
    alignSelf: "stretch",
    textAlign: "center",
  },
  quickAccessFooter: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  quickAccessFooterText: {
    fontSize: 13,
    fontWeight: "700",
  },
  quickAccessFooterAccent: {
    width: 28,
    height: 8,
    borderRadius: 999,
  },
  programsHeroCard: {
    minHeight: 322,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 18,
    borderRadius: 18,
  },
  programsHeroImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 172,
    zIndex: 0,
  },
  programsHeroImageAsset: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  programsHeroImageShade: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  programsHeroImageFade: {
    position: "absolute",
    top: 66,
    left: 0,
    right: 0,
    height: 116,
    zIndex: 1,
  },
  programsHeroImageFadeStep: {
    flex: 1,
  },
  programsHeroTopAccent: {
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    zIndex: 3,
  },
  programsHeroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 16,
    marginBottom: 114,
    zIndex: 2,
  },
  programsHeroEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  programsHeroEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  programsHeroEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  programsHeroAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  programsHeroContent: {
    gap: 8,
    zIndex: 2,
  },
  programsHeroTitle: {
    color: "#ffffff",
    lineHeight: 28,
  },
  programsHeroDescription: {
    fontSize: 14,
    lineHeight: 21,
  },
  programsHeroMetricsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  programsHeroMetricCard: {
    flex: 1,
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: "center",
  },
  programsHeroMetricValue: {
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 24,
  },
  programsHeroMetricLabel: {
    fontSize: 9,
    fontWeight: "800",
    lineHeight: 11,
    textTransform: "uppercase",
    marginTop: 5,
  },
  exerciseLibraryHeroCard: {
    minHeight: 322,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 18,
    borderRadius: 18,
  },
  exerciseLibraryHeroTopAccent: {
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    zIndex: 3,
  },
  exerciseLibraryHeroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 16,
    marginBottom: 114,
    zIndex: 2,
  },
  exerciseLibraryHeroEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  exerciseLibraryHeroEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  exerciseLibraryHeroEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  exerciseLibraryHeroAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseLibraryHeroImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 172,
    zIndex: 0,
  },
  exerciseLibraryHeroImageAsset: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    opacity: 0.68,
  },
  exerciseLibraryHeroImageShade: {
    flex: 1,
    opacity: 0.12,
  },
  exerciseLibraryHeroImageFade: {
    position: "absolute",
    top: 66,
    left: 0,
    right: 0,
    height: 116,
    zIndex: 1,
  },
  exerciseLibraryHeroContent: {
    zIndex: 2,
  },
  exerciseLibraryHeroTitle: {
    color: "#ffffff",
    lineHeight: 26,
  },
  exerciseLibraryHeroDescription: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
  exerciseLibraryHeroMetricsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  exerciseLibraryHeroMetricCard: {
    flex: 1,
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: "center",
  },
  exerciseLibraryHeroMetricValue: {
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 24,
  },
  exerciseLibraryHeroMetricLabel: {
    fontSize: 9,
    fontWeight: "800",
    lineHeight: 11,
    textTransform: "uppercase",
    marginTop: 5,
  },
  personalRecordsHeroCard: {
    minHeight: 322,
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 18,
    borderRadius: 18,
  },
  personalRecordsHeroTopAccent: {
    left: 0,
    right: 0,
    height: 3,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    zIndex: 3,
  },
  personalRecordsHeroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 16,
    marginBottom: 114,
    zIndex: 2,
  },
  personalRecordsHeroEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  personalRecordsHeroEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  personalRecordsHeroEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  personalRecordsHeroAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  personalRecordsHeroImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 172,
    zIndex: 0,
  },
  personalRecordsHeroImageAsset: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    opacity: 0.74,
  },
  personalRecordsHeroImageShade: {
    flex: 1,
    opacity: 0.08,
  },
  personalRecordsHeroImageFade: {
    position: "absolute",
    top: 66,
    left: 0,
    right: 0,
    height: 116,
    zIndex: 1,
  },
  personalRecordsHeroContent: {
    zIndex: 2,
  },
  personalRecordsHeroTitle: {
    color: "#ffffff",
    lineHeight: 26,
  },
  personalRecordsHeroDescription: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
});
