import { StyleSheet } from "react-native";

// Layout only; colours come from `theme` in the components.
export default StyleSheet.create({
  card: {
    borderRadius: 20,
    borderWidth: 1,
    paddingVertical: 15,
    paddingHorizontal: 16,
    gap: 13,
  },
  header: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  headerCopy: { flex: 1, minWidth: 0, gap: 2 },
  eyebrow: { fontSize: 10.5, fontWeight: "800", letterSpacing: 1.4, textTransform: "uppercase" },
  suggested: { fontSize: 11, fontWeight: "700", lineHeight: 14 },
  edit: { fontSize: 11.5, fontWeight: "800" },

  tiles: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  tile: {
    flex: 1,
    minWidth: 0,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 11,
    paddingHorizontal: 10,
    gap: 3,
  },
  // Four or more sessions sit three to a row, so a name has room to be read.
  tileWrapped: { flexBasis: "30%", flexGrow: 1 },
  tileTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", minHeight: 12 },
  nextBadge: { fontSize: 8.5, fontWeight: "900", letterSpacing: 0.6, textTransform: "uppercase" },
  tileName: { fontSize: 14.5, fontWeight: "800", lineHeight: 18 },
  tileDate: { fontSize: 10.5, fontWeight: "700", lineHeight: 14 },

  cta: {
    height: 48,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 14,
  },
  ctaText: { flexShrink: 1, fontSize: 14.5, fontWeight: "800" },
  ctaMeta: { flexShrink: 0, fontSize: 13, fontWeight: "700" },

  empty: { gap: 6, alignItems: "flex-start" },
  emptyTitle: { fontSize: 15, fontWeight: "800", lineHeight: 20 },
  emptyBody: { fontSize: 12.5, fontWeight: "600", lineHeight: 17 },
  chooseButton: {
    marginTop: 6,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  chooseText: { fontSize: 13, fontWeight: "800" },

  // Repeat also
  alsoHead: { marginTop: 18, fontSize: 10, fontWeight: "800", letterSpacing: 1.8, textTransform: "uppercase" },
  alsoRail: { gap: 8, paddingRight: 4 },
  alsoScroll: { marginTop: 9 },
  chip: {
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  chipCopy: { gap: 1 },
  chipName: { fontSize: 13, fontWeight: "800", lineHeight: 16 },
  chipMeta: { fontSize: 10.5, fontWeight: "700", lineHeight: 13 },

  // The editor
  sheetTitle: { fontSize: 18, fontWeight: "800", lineHeight: 23 },
  sheetBody: { fontSize: 13, fontWeight: "600", lineHeight: 18, marginTop: 4 },
  sheetCount: { fontSize: 11, fontWeight: "800", letterSpacing: 0.4, marginTop: 12 },
  sheetList: { marginTop: 10, maxHeight: 360 },
  sheetRow: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  sheetOrder: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetOrderText: { fontSize: 11, fontWeight: "900" },
  sheetRowName: { flex: 1, minWidth: 0, fontSize: 14, fontWeight: "700" },
  sheetEmpty: { fontSize: 13, fontWeight: "600", lineHeight: 18, marginTop: 12 },
  sheetActions: { marginTop: 8, gap: 10 },
  sheetSave: { height: 48, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  sheetSaveText: { fontSize: 14.5, fontWeight: "800" },
  sheetReset: { alignSelf: "center", paddingVertical: 6 },
  sheetResetText: { fontSize: 12.5, fontWeight: "800" },
});
