import { StyleSheet } from "react-native";

const EXERCISE_ROW_HEIGHT = 62;
const EXERCISE_PREVIEW_GAP = 14;
const EXERCISE_PREVIEW_WIDTH = Math.round(EXERCISE_ROW_HEIGHT * (503 / 647));
const VISIBLE_EXERCISE_COUNT = 10;
const LIST_VIEWPORT_HEIGHT = EXERCISE_ROW_HEIGHT * VISIBLE_EXERCISE_COUNT;

export default StyleSheet.create({
  card: {
    marginHorizontal: 0,
    marginVertical: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
  },
  headerIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
  },
  eyebrow: {
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  title: {
    lineHeight: 26,
  },
  countBadge: {
    minWidth: 92,
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  countBadgeText: {
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  countBadgeNumber: {
    fontSize: 12,
    fontWeight: "900",
  },
  description: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
    maxWidth: 280,
  },
  divider: {
    height: 1,
    opacity: 0.55,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
  },
  searchBox: {
    flex: 1,
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 11,
  },
  searchInput: {
    flex: 1,
    minHeight: 38,
    paddingHorizontal: 9,
    paddingVertical: 0,
    fontSize: 13,
    fontWeight: "600",
  },
  filterButton: {
    width: 38,
    height: 38,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  filterScroll: {
    flexGrow: 0,
  },
  filterSections: {
    gap: 13,
    paddingBottom: 14,
  },
  filterSection: {
    gap: 7,
  },
  filterSectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 14,
  },
  filterSectionAccent: {
    width: 14,
    height: 2,
    borderRadius: 999,
  },
  filterSectionLabel: {
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 13,
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  filterContent: {
    paddingHorizontal: 14,
    gap: 8,
  },
  groupFilter: {
    minHeight: 28,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  groupFilterText: {
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    textTransform: "uppercase",
  },
  muscleRoleLegend: {
    marginHorizontal: 14,
    marginBottom: 6,
    gap: 8,
  },
  muscleRoleLegendItem: {
    borderLeftWidth: 3,
    paddingLeft: 9,
    paddingVertical: 1,
    gap: 1,
  },
  muscleRoleLegendText: {
    fontSize: 10,
    lineHeight: 14,
  },
  muscleRoleLegendLabel: {
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 13,
    textTransform: "uppercase",
  },
  customExerciseAction: {
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 8,
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  tableHeaderPreview: {
    width: EXERCISE_PREVIEW_WIDTH + EXERCISE_PREVIEW_GAP,
  },
  tableHeaderExercise: {
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  listScroll: {
    height: LIST_VIEWPORT_HEIGHT,
    flexGrow: 0,
  },
  listContent: {
    paddingBottom: 0,
  },
  exerciseRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: EXERCISE_ROW_HEIGHT,
    borderTopWidth: 1,
    paddingLeft: 18,
    paddingRight: 8,
    paddingVertical: 0,
    overflow: "hidden",
  },
  exerciseRowLast: {
    borderBottomWidth: 0,
  },
  exerciseRowSelected: {
    opacity: 0.58,
  },
  exercisePreviewBodyMap: {
    width: EXERCISE_PREVIEW_WIDTH,
    maxWidth: EXERCISE_PREVIEW_WIDTH,
    height: EXERCISE_ROW_HEIGHT,
    alignSelf: "center",
    marginRight: EXERCISE_PREVIEW_GAP,
  },
  exerciseBody: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingRight: 0,
    paddingVertical: 8,
  },
  exerciseTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minWidth: 0,
  },
  exerciseName: {
    flex: 1,
    flexShrink: 1,
    marginRight: 6,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 20,
  },
  exerciseStatusBadge: {
    minHeight: 18,
    borderRadius: 999,
    paddingHorizontal: 7,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  exerciseStatusBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    lineHeight: 11,
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  muscleBadgeRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 5,
    marginTop: 4,
  },
  muscleBadge: {
    minHeight: 16,
    borderRadius: 999,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  primaryMuscleBadge: {
    minWidth: 58,
  },
  secondaryMuscleBadge: {
    minWidth: 74,
  },
  muscleBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    lineHeight: 11,
    includeFontPadding: false,
    textAlign: "center",
    flexShrink: 0,
  },
  exerciseBodyMapModal: {
    width: "94%",
    maxHeight: "92%",
    paddingHorizontal: 18,
  },
  exerciseBodyMapModalBody: {
    flexGrow: 0,
    gap: 14,
  },
  exerciseBodyMapModalBadges: {
    justifyContent: "center",
    marginTop: 0,
  },
  exerciseBodyMapModalFigures: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 16,
    minWidth: 0,
  },
  exerciseBodyMapModalFigure: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
  },
  exerciseBodyMapModalFigureLabel: {
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  exerciseBodyMapModalPreview: {
    width: "100%",
    maxWidth: 138,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 18,
    minHeight: LIST_VIEWPORT_HEIGHT,
  },
  emptyTitle: {
    textAlign: "center",
    marginBottom: 8,
  },
  emptyBody: {
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 260,
  },
  pickerShell: {
    flex: 1,
    gap: 14,
  },
  pickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 2,
    paddingTop: 2,
  },
  pickerBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  pickerEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 13,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  pickerTitle: {
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 27,
  },
  pickerCountPill: {
    minHeight: 30,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerCountText: {
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 14,
  },
  pickerCountNumber: {
    fontSize: 11,
    fontWeight: "900",
    lineHeight: 14,
    fontVariant: ["tabular-nums"],
  },
  pickerDivider: {
    height: 1,
  },
  pickerSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pickerSearchBox: {
    flex: 1,
    height: 46,
    borderWidth: 1,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
  },
  pickerSearchInput: {
    flex: 1,
    height: 46,
    paddingHorizontal: 10,
    paddingVertical: 0,
    fontSize: 14,
    fontWeight: "700",
  },
  pickerFilterButton: {
    width: 46,
    height: 46,
    borderWidth: 1,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerFilterBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    minWidth: 17,
    height: 17,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerFilterBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    lineHeight: 11,
    includeFontPadding: false,
    fontVariant: ["tabular-nums"],
  },
  pickerChipScroll: {
    flexGrow: 0,
    marginHorizontal: -2,
  },
  pickerChipContent: {
    gap: 7,
    paddingHorizontal: 2,
  },
  pickerFocusChip: {
    minHeight: 32,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerFocusChipText: {
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 14,
  },
  pickerFocusChipTextActive: {
    fontWeight: "800",
  },
  pickerSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 2,
  },
  pickerSectionEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 13,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  pickerLegend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  pickerLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  pickerLegendDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  pickerLegendText: {
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
  },
  pickerExerciseCard: {
    borderWidth: 1,
    borderRadius: 20,
    overflow: "hidden",
  },
  pickerExerciseRow: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 69,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  pickerPreviewTile: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  pickerPreviewBodyMap: {
    width: 34,
    maxWidth: 34,
    height: 44,
    alignSelf: "center",
  },
  pickerExerciseBody: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  pickerExerciseTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
    gap: 7,
  },
  pickerExerciseName: {
    flex: 1,
    minWidth: 0,
    fontSize: 14.5,
    fontWeight: "800",
    lineHeight: 18,
  },
  pickerCustomBadge: {
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  pickerCustomBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    lineHeight: 11,
    includeFontPadding: false,
    textTransform: "uppercase",
  },
  pickerMuscleLine: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
    gap: 8,
    overflow: "hidden",
  },
  pickerMuscleChunk: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
    gap: 4,
    flexShrink: 1,
  },
  pickerMuscleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    flexShrink: 0,
  },
  pickerMuscleText: {
    minWidth: 0,
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 14,
  },
  pickerAddedText: {
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 14,
  },
  pickerAddButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pickerExerciseDivider: {
    position: "absolute",
    left: 72,
    right: 16,
    bottom: 0,
    height: StyleSheet.hairlineWidth,
  },
  pickerEmptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 42,
    paddingHorizontal: 18,
    minHeight: 180,
  },
  pickerFooter: {
    marginHorizontal: -18,
    marginBottom: -16,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 16,
    borderTopWidth: 1,
  },
  pickerCustomButton: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: "dashed",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  pickerCustomButtonText: {
    fontSize: 13.5,
    fontWeight: "800",
    lineHeight: 17,
  },
  pickerModalMusclesCard: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    gap: 13,
  },
  pickerModalMusclesTitle: {
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 13,
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  pickerModalMuscleRole: {
    gap: 8,
  },
  pickerModalMuscleRoleHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  pickerModalMuscleRoleTitle: {
    fontSize: 11,
    fontWeight: "900",
    lineHeight: 14,
    textTransform: "uppercase",
  },
  pickerModalMuscleChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  pickerModalMuscleChip: {
    minHeight: 24,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerModalMuscleChipText: {
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
  },
  pickerModalMuscleEmptyText: {
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  pickerModalAddButton: {
    minHeight: 48,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  pickerModalAddButtonText: {
    fontSize: 13.5,
    fontWeight: "900",
    lineHeight: 17,
  },
});
