import { StyleSheet } from "react-native";

const EXERCISE_ROW_HEIGHT = 62;
const VISIBLE_EXERCISE_COUNT = 10;
const LIST_VIEWPORT_HEIGHT = EXERCISE_ROW_HEIGHT * VISIBLE_EXERCISE_COUNT;

export default StyleSheet.create({
  card: {
    marginHorizontal: 0,
    marginVertical: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 1,
    borderRadius: 18,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
  },
  headerIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
  },
  eyebrow: {
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  title: {
    lineHeight: 26,
  },
  countBadge: {
    minWidth: 92,
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  countBadgeText: {
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  countBadgeNumber: {
    fontSize: 12,
    fontWeight: "900",
  },
  description: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
    maxWidth: 280,
  },
  divider: {
    height: 1,
    opacity: 0.55,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
  },
  searchBox: {
    flex: 1,
    minHeight: 38,
    borderWidth: 1,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 11,
  },
  searchInput: {
    flex: 1,
    minHeight: 38,
    paddingHorizontal: 9,
    paddingVertical: 0,
    fontSize: 13,
    fontWeight: "600",
  },
  filterButton: {
    width: 38,
    height: 38,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  filterScroll: {
    flexGrow: 0,
    paddingBottom: 12,
  },
  filterContent: {
    paddingHorizontal: 14,
    gap: 8,
  },
  groupFilter: {
    minHeight: 28,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  groupFilterText: {
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    textTransform: "uppercase",
  },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  tableHeaderIndex: {
    width: 44,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  tableHeaderExercise: {
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  tableHeaderMuscles: {
    width: 112,
    fontSize: 11,
    fontWeight: "800",
    textAlign: "right",
    textTransform: "uppercase",
  },
  listScroll: {
    height: LIST_VIEWPORT_HEIGHT,
    flexGrow: 0,
  },
  listContent: {
    paddingBottom: 0,
  },
  exerciseRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: EXERCISE_ROW_HEIGHT,
    borderTopWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  exerciseRowLast: {
    borderBottomWidth: 0,
  },
  exerciseIndexText: {
    width: 44,
    fontSize: 13,
    fontWeight: "800",
  },
  exerciseBody: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingRight: 8,
  },
  exerciseName: {
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 19,
  },
  exerciseMetaText: {
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 14,
    marginTop: 2,
    textTransform: "uppercase",
  },
  muscleSummary: {
    width: 112,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  muscleBadge: {
    minWidth: 34,
    minHeight: 17,
    borderRadius: 999,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  muscleBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 12,
  },
  rowChevron: {
    width: 10,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 16,
    textAlign: "right",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 18,
    minHeight: LIST_VIEWPORT_HEIGHT,
  },
  emptyTitle: {
    textAlign: "center",
    marginBottom: 8,
  },
  emptyBody: {
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 260,
  },
});
