import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    paddingHorizontal: 18,
    marginBottom: 12,
    gap: 12,
  },
  stateCard: {
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 18,
    overflow: "hidden",
  },
  emptyState: {
    gap: 18,
  },
  emptyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  emptyHeaderTitle: {
    padding: 0,
    fontSize: 31,
    lineHeight: 29,
  },
  notificationButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationBadgeText: {
    fontSize: 9,
    lineHeight: 11,
    fontWeight: "900",
  },
  emptyTodayCard: {
    borderRadius: 30,
    paddingHorizontal: 22,
    paddingTop: 28,
    paddingBottom: 18,
    gap: 17,
  },
  stateAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 4,
  },
  stateEyebrow: {
    fontWeight: "800",
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  loadingState: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 12,
  },
  loadingCopy: {
    marginTop: 10,
    textAlign: "center",
  },
  emptyContent: {
    alignItems: "flex-start",
  },
  emptyTitle: {
    padding: 0,
    fontSize: 23,
    lineHeight: 28,
    fontWeight: "800",
  },
  quickStartButton: {
    minHeight: 58,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 20,
    paddingRight: 9,
  },
  quickStartButtonText: {
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
  },
  quickStartArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.13)",
  },
  todayWorkoutList: {
    gap: 10,
    marginHorizontal: -22,
    marginTop: -28,
  },
  scheduleDivider: {
    minHeight: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  scheduleLine: {
    flex: 1,
    height: 1,
  },
  scheduleText: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "800",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  nextWorkoutCard: {
    minHeight: 78,
    borderWidth: 1,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 9,
  },
  nextWorkoutDate: {
    width: 50,
    height: 58,
    borderWidth: 1,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  nextWorkoutWeekday: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "900",
    letterSpacing: 1,
  },
  nextWorkoutDay: {
    padding: 0,
    fontSize: 20,
    lineHeight: 23,
    fontWeight: "800",
  },
  nextWorkoutContent: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  nextWorkoutEyebrow: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  nextWorkoutTitle: {
    padding: 0,
    fontSize: 16,
    lineHeight: 19,
    fontWeight: "800",
  },
  calendarButton: {
    minHeight: 50,
    borderWidth: 1,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingHorizontal: 15,
  },
  calendarButtonText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
});
