import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    marginTop: 14,
    marginHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
  },
  imageZone: {
    position: "relative",
    height: 158,
    overflow: "hidden",
  },
  completedImageZone: {
    height: 230,
  },
  completedImageTint: {
    ...StyleSheet.absoluteFillObject,
  },
  image: {
    width: "100%",
    height: "100%",
  },
  chip: {
    position: "absolute",
    top: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 11,
    borderWidth: 1,
  },
  chipLeft: {
    left: 14,
  },
  chipRight: {
    right: 14,
    borderWidth: 0,
  },
  completedChip: {
    gap: 7,
  },
  chipDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
  },
  chipLabel: {
    fontSize: 9.5,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  typeChipLabel: {
    fontSize: 10.5,
    fontWeight: "800",
  },
  overlayText: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: 8,
    gap: 3,
  },
  completedCheckCircle: {
    position: "absolute",
    top: 17,
    right: 20,
    width: 62,
    height: 62,
    borderRadius: 31,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -0.4,
    lineHeight: 29,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  metaItemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    marginHorizontal: 8,
  },
  metaText: {
    fontSize: 12,
    fontWeight: "700",
  },
  completedMetaText: {
    fontWeight: "800",
  },
  buttonZone: {
    paddingTop: 14,
    paddingHorizontal: 18,
    paddingBottom: 16,
  },
  completedCard: {
    borderWidth: 1.25,
  },
  completedBody: {
    paddingTop: 20,
    paddingHorizontal: 18,
    paddingBottom: 20,
    gap: 20,
  },
  completedSummary: {
    minHeight: 100,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  completedSummaryIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
  },
  completedSummaryCopy: {
    flex: 1,
    minWidth: 0,
  },
  completedSummaryTitle: {
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 25,
  },
  completedSummarySubtitle: {
    marginTop: 2,
    fontSize: 13.5,
    fontWeight: "600",
    lineHeight: 19,
  },
  summaryButton: {
    minHeight: 66,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  summaryButtonText: {
    fontSize: 18,
    fontWeight: "900",
  },
  startButton: {
    height: 50,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 6,
  },
  playTriangle: {
    width: 0,
    height: 0,
    borderTopWidth: 6,
    borderBottomWidth: 6,
    borderLeftWidth: 10,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
  },
  startButtonText: {
    fontSize: 15,
    fontWeight: "800",
  },
  divider: {
    height: 1,
    marginHorizontal: 18,
  },
  upNextRow: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  upNextRowBare: {
    paddingHorizontal: 0,
    paddingTop: 4,
    paddingBottom: 0,
  },
  dateBadge: {
    width: 44,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
    flexShrink: 0,
  },
  dateBadgeWeekday: {
    fontSize: 8.5,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  dateBadgeNumber: {
    fontSize: 16,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  upNextTextColumn: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  upNextEyebrow: {
    fontSize: 9.5,
    fontWeight: "800",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  upNextTitle: {
    fontSize: 14.5,
    fontWeight: "800",
  },
  emptyCard: {
    alignItems: "center",
    paddingTop: 28,
    paddingBottom: 20,
    paddingHorizontal: 20,
    gap: 6,
  },
  emptyIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "800",
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 12.5,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 10,
  },
  emptyStartButton: {
    alignSelf: "stretch",
    marginBottom: 4,
  },
});
