-- Adds the cloud workout type catalog used by workout_type_instance.workout_type.
-- Run this against the Supabase project before shipping clients that depend on
-- remotely controlled workout type visibility or display names.

create table if not exists public.workout_type (
  id bigint generated by default as identity not null,
  type text,
  display_name text,
  is_active boolean not null default false,
  constraint workout_type_pkey primary key (id)
);

alter table public.workout_type
  add column if not exists type text;

alter table public.workout_type
  add column if not exists display_name text;

alter table public.workout_type
  add column if not exists is_active boolean not null default false;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'workout_type'
      and column_name = 'name'
  ) then
    update public.workout_type
    set type = btrim(name)
    where btrim(coalesce(type, '')) = ''
      and btrim(coalesce(name, '')) <> '';
  end if;
end;
$$;

update public.workout_type
set type = btrim(type)
where type is not null
  and type <> btrim(type);

delete from public.workout_type
where btrim(coalesce(type, '')) = '';

with seed_workout_types(type, display_name, is_active) as (
  values
    ('Resistance', 'Resistance', true),
    ('Run', 'Run', true),
    ('Upperbody', 'Upperbody', false),
    ('Legs', 'Legs', false),
    ('StrengthTraining', 'StrengthTraining', false)
)
insert into public.workout_type (type, display_name, is_active)
select
  seed_workout_types.type,
  seed_workout_types.display_name,
  seed_workout_types.is_active
from seed_workout_types
where not exists (
  select 1
  from public.workout_type
  where public.workout_type.type = seed_workout_types.type
);

do $$
begin
  if to_regclass('public.workout_type_instance') is not null then
    insert into public.workout_type (type, display_name, is_active)
    select distinct
      btrim(workout_type_instance.workout_type),
      btrim(workout_type_instance.workout_type),
      false
    from public.workout_type_instance
    where btrim(coalesce(workout_type_instance.workout_type, '')) <> ''
      and not exists (
        select 1
        from public.workout_type
        where public.workout_type.type = btrim(workout_type_instance.workout_type)
      );
  end if;
end;
$$;

update public.workout_type
set display_name = type
where btrim(coalesce(display_name, '')) = '';

with ranked_workout_types as (
  select
    id,
    row_number() over (
      partition by type
      order by is_active desc, id asc
    ) as duplicate_rank
  from public.workout_type
)
delete from public.workout_type
using ranked_workout_types
where public.workout_type.id = ranked_workout_types.id
  and ranked_workout_types.duplicate_rank > 1;

alter table public.workout_type
  alter column type set not null;

alter table public.workout_type
  drop constraint if exists workout_type_name_key;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'workout_type_type_key'
      and conrelid = 'public.workout_type'::regclass
  ) then
    alter table public.workout_type
      add constraint workout_type_type_key unique (type);
  end if;
end;
$$;

create index if not exists workout_type_active_idx
  on public.workout_type (is_active, type);

do $$
begin
  if to_regclass('public.workout_type_instance') is not null then
    execute '
      create index if not exists workout_type_instance_workout_type_idx
        on public.workout_type_instance (workout_type)
        where workout_type is not null
    ';

    if not exists (
      select 1
      from pg_constraint
      where conname = 'workout_type_instance_workout_type_fkey'
        and conrelid = 'public.workout_type_instance'::regclass
    ) then
      alter table public.workout_type_instance
        add constraint workout_type_instance_workout_type_fkey
        foreign key (workout_type)
        references public.workout_type(type)
        on update cascade
        on delete restrict;
    end if;
  end if;
end;
$$;

alter table public.workout_type enable row level security;

drop policy if exists "Workout types are viewable by authenticated users"
  on public.workout_type;

create policy "Workout types are viewable by authenticated users"
on public.workout_type
for select
to authenticated
using (true);
