-- Adds body map region metadata for exercise catalog muscle highlights.
--
-- Source of truth remains:
--   public."Exercise" -> public."Muscle_Activation" -> public."Muscle"
--
-- These tables only describe how concrete muscles map to visual body-map
-- regions. The app can derive primary/secondary highlights from
-- Muscle_Activation.activation_level.

begin;

create table if not exists public.body_map_region (
  id bigint generated by default as identity not null,
  region_key text not null,
  body_view text not null,
  name text not null,
  constraint body_map_region_pkey primary key (id),
  constraint body_map_region_view_key_unique unique (body_view, region_key),
  constraint body_map_region_key_not_blank check (btrim(region_key) <> ''),
  constraint body_map_region_name_not_blank check (btrim(name) <> ''),
  constraint body_map_region_body_view_valid
    check (body_view in ('front', 'back'))
);

alter table public.body_map_region
  add column if not exists region_key text;

alter table public.body_map_region
  add column if not exists body_view text;

alter table public.body_map_region
  add column if not exists name text;

update public.body_map_region
set
  region_key = lower(regexp_replace(btrim(region_key), '[^a-zA-Z0-9]+', '_', 'g')),
  body_view = lower(btrim(body_view)),
  name = btrim(name)
where region_key is not null
  and body_view is not null
  and name is not null;

delete from public.body_map_region
where btrim(coalesce(region_key, '')) = ''
   or btrim(coalesce(body_view, '')) not in ('front', 'back')
   or btrim(coalesce(name, '')) = '';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_view_key_unique'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_view_key_unique
      unique (body_view, region_key);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_key_not_blank'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_key_not_blank
      check (btrim(region_key) <> '');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_name_not_blank'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_name_not_blank
      check (btrim(name) <> '');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_body_view_valid'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_body_view_valid
      check (body_view in ('front', 'back'));
  end if;
end $$;

with seed_regions(body_view, region_key, name) as (
  values
    ('front', 'abs', 'Abs'),
    ('front', 'adductors', 'Adductors'),
    ('front', 'biceps', 'Biceps'),
    ('front', 'forearms', 'Forearms'),
    ('front', 'front_delts', 'Front delts'),
    ('front', 'obliques', 'Obliques'),
    ('front', 'pecs', 'Pecs'),
    ('front', 'quads', 'Quads'),
    ('front', 'side_delts', 'Side delts'),
    ('front', 'upper_traps', 'Upper traps'),
    ('back', 'adductors', 'Adductors'),
    ('back', 'calves', 'Calves'),
    ('back', 'glutes', 'Glutes'),
    ('back', 'hamstrings', 'Hamstrings'),
    ('back', 'infraspinatus', 'Infraspinatus'),
    ('back', 'lats', 'Lats'),
    ('back', 'lower_back', 'Lower back'),
    ('back', 'rear_delts', 'Rear delts'),
    ('back', 'side_delts', 'Side delts'),
    ('back', 'teres_major', 'Teres major'),
    ('back', 'teres_minor', 'Teres minor'),
    ('back', 'triceps', 'Triceps'),
    ('back', 'upper_traps', 'Upper traps')
)
insert into public.body_map_region (body_view, region_key, name)
select
  seed_regions.body_view,
  seed_regions.region_key,
  seed_regions.name
from seed_regions
on conflict (body_view, region_key) do update
set name = excluded.name;

create table if not exists public.muscle_body_map_region (
  muscle_id bigint not null,
  body_map_region_id bigint not null,
  constraint muscle_body_map_region_pkey
    primary key (muscle_id, body_map_region_id),
  constraint muscle_body_map_region_muscle_fkey
    foreign key (muscle_id)
    references public."Muscle"(id)
    on update cascade
    on delete cascade,
  constraint muscle_body_map_region_region_fkey
    foreign key (body_map_region_id)
    references public.body_map_region(id)
    on update cascade
    on delete cascade
);

alter table public.muscle_body_map_region
  add column if not exists muscle_id bigint;

alter table public.muscle_body_map_region
  add column if not exists body_map_region_id bigint;

delete from public.muscle_body_map_region
where muscle_id is null
   or body_map_region_id is null;

alter table public.muscle_body_map_region
  alter column muscle_id set not null;

alter table public.muscle_body_map_region
  alter column body_map_region_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'muscle_body_map_region_pkey'
      and conrelid = 'public.muscle_body_map_region'::regclass
  ) then
    alter table public.muscle_body_map_region
      add constraint muscle_body_map_region_pkey
      primary key (muscle_id, body_map_region_id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'muscle_body_map_region_muscle_fkey'
      and conrelid = 'public.muscle_body_map_region'::regclass
  ) then
    alter table public.muscle_body_map_region
      add constraint muscle_body_map_region_muscle_fkey
      foreign key (muscle_id)
      references public."Muscle"(id)
      on update cascade
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'muscle_body_map_region_region_fkey'
      and conrelid = 'public.muscle_body_map_region'::regclass
  ) then
    alter table public.muscle_body_map_region
      add constraint muscle_body_map_region_region_fkey
      foreign key (body_map_region_id)
      references public.body_map_region(id)
      on update cascade
      on delete cascade;
  end if;
end $$;

create index if not exists muscle_body_map_region_region_id_idx
  on public.muscle_body_map_region (body_map_region_id);

alter table public.body_map_region enable row level security;
alter table public.muscle_body_map_region enable row level security;

grant select on public.body_map_region to authenticated;
grant select on public.muscle_body_map_region to authenticated;

drop policy if exists "Body map regions are viewable by authenticated users"
  on public.body_map_region;

create policy "Body map regions are viewable by authenticated users"
on public.body_map_region
for select
to authenticated
using (true);

drop policy if exists "Muscle body map regions are viewable by authenticated users"
  on public.muscle_body_map_region;

create policy "Muscle body map regions are viewable by authenticated users"
on public.muscle_body_map_region
for select
to authenticated
using (true);

-- Optional mapping seed template:
-- Add rows here once the exact public."Muscle".name values are confirmed.
--
-- with seed_mappings(muscle_name, body_view, region_key) as (
--   values
--     ('Pectoralis Major', 'front', 'pecs'),
--     ('Anterior Deltoid', 'front', 'front_delts'),
--     ('Lateral Deltoid', 'front', 'side_delts'),
--     ('Lateral Deltoid', 'back', 'side_delts'),
--     ('Triceps', 'back', 'triceps')
-- )
-- insert into public.muscle_body_map_region (muscle_id, body_map_region_id)
-- select
--   "Muscle".id,
--   body_map_region.id
-- from seed_mappings
-- join public."Muscle"
--   on lower("Muscle".name) = lower(seed_mappings.muscle_name)
-- join public.body_map_region
--   on body_map_region.body_view = seed_mappings.body_view
--  and body_map_region.region_key = seed_mappings.region_key
-- on conflict (muscle_id, body_map_region_id) do nothing;

commit;
