-- Adds social feed persistence for automatically generated workout summaries.
--
-- Run after:
--   docs/supabase-social-search.sql
--   the sync schema that creates public.workout_type_instance
--
-- Workout summary posts store a snapshot payload so feed posts do not change
-- when a completed workout is edited later.

begin;

create table if not exists public.social_post (
  id bigint generated by default as identity not null,
  author_id uuid not null,
  post_type text not null default 'workout_summary',
  source_workout_type_instance_id bigint not null,
  workout_type text not null,
  title text not null,
  body text not null default '',
  payload jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz,
  constraint social_post_pkey primary key (id),
  constraint social_post_author_fkey
    foreign key (author_id)
    references public.profiles(id)
    on update cascade
    on delete cascade,
  constraint social_post_source_workout_fkey
    foreign key (source_workout_type_instance_id)
    references public.workout_type_instance(id)
    on update cascade
    on delete cascade,
  constraint social_post_source_unique
    unique (author_id, post_type, source_workout_type_instance_id),
  constraint social_post_type_valid
    check (post_type in ('workout_summary')),
  constraint social_post_workout_type_not_blank
    check (btrim(workout_type) <> ''),
  constraint social_post_title_not_blank
    check (btrim(title) <> ''),
  constraint social_post_payload_object
    check (jsonb_typeof(payload) = 'object')
);

alter table public.social_post
  add column if not exists author_id uuid;

alter table public.social_post
  add column if not exists post_type text;

alter table public.social_post
  add column if not exists source_workout_type_instance_id bigint;

alter table public.social_post
  add column if not exists workout_type text;

alter table public.social_post
  add column if not exists title text;

alter table public.social_post
  add column if not exists body text;

alter table public.social_post
  add column if not exists payload jsonb;

alter table public.social_post
  add column if not exists completed_at timestamptz;

alter table public.social_post
  add column if not exists created_at timestamptz;

alter table public.social_post
  add column if not exists updated_at timestamptz;

alter table public.social_post
  add column if not exists deleted_at timestamptz;

alter table public.social_post
  alter column post_type set default 'workout_summary';

alter table public.social_post
  alter column body set default '';

alter table public.social_post
  alter column payload set default '{}'::jsonb;

alter table public.social_post
  alter column completed_at set default timezone('utc', now());

alter table public.social_post
  alter column created_at set default timezone('utc', now());

alter table public.social_post
  alter column updated_at set default timezone('utc', now());

update public.social_post
set
  post_type = coalesce(nullif(btrim(post_type), ''), 'workout_summary'),
  workout_type = nullif(btrim(workout_type), ''),
  title = nullif(btrim(title), ''),
  body = coalesce(body, ''),
  payload = coalesce(payload, '{}'::jsonb),
  completed_at = coalesce(completed_at, created_at, timezone('utc', now())),
  created_at = coalesce(created_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, created_at, timezone('utc', now()));

alter table public.social_post
  alter column author_id set not null;

alter table public.social_post
  alter column post_type set not null;

alter table public.social_post
  alter column source_workout_type_instance_id set not null;

alter table public.social_post
  alter column workout_type set not null;

alter table public.social_post
  alter column title set not null;

alter table public.social_post
  alter column body set not null;

alter table public.social_post
  alter column payload set not null;

alter table public.social_post
  alter column completed_at set not null;

alter table public.social_post
  alter column created_at set not null;

alter table public.social_post
  alter column updated_at set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_author_fkey'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_author_fkey
      foreign key (author_id)
      references public.profiles(id)
      on update cascade
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_source_workout_fkey'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_source_workout_fkey
      foreign key (source_workout_type_instance_id)
      references public.workout_type_instance(id)
      on update cascade
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_source_unique'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_source_unique
      unique (author_id, post_type, source_workout_type_instance_id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_type_valid'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_type_valid
      check (post_type in ('workout_summary'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_workout_type_not_blank'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_workout_type_not_blank
      check (btrim(workout_type) <> '');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_title_not_blank'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_title_not_blank
      check (btrim(title) <> '');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_payload_object'
      and conrelid = 'public.social_post'::regclass
  ) then
    alter table public.social_post
      add constraint social_post_payload_object
      check (jsonb_typeof(payload) = 'object');
  end if;
end $$;

create table if not exists public.social_post_like (
  post_id bigint not null,
  user_id uuid not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint social_post_like_pkey primary key (post_id, user_id),
  constraint social_post_like_post_fkey
    foreign key (post_id)
    references public.social_post(id)
    on update cascade
    on delete cascade,
  constraint social_post_like_user_fkey
    foreign key (user_id)
    references public.profiles(id)
    on update cascade
    on delete cascade
);

alter table public.social_post_like
  add column if not exists post_id bigint;

alter table public.social_post_like
  add column if not exists user_id uuid;

alter table public.social_post_like
  add column if not exists created_at timestamptz;

alter table public.social_post_like
  alter column created_at set default timezone('utc', now());

update public.social_post_like
set created_at = coalesce(created_at, timezone('utc', now()));

alter table public.social_post_like
  alter column post_id set not null;

alter table public.social_post_like
  alter column user_id set not null;

alter table public.social_post_like
  alter column created_at set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_like_pkey'
      and conrelid = 'public.social_post_like'::regclass
  ) then
    alter table public.social_post_like
      add constraint social_post_like_pkey
      primary key (post_id, user_id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_like_post_fkey'
      and conrelid = 'public.social_post_like'::regclass
  ) then
    alter table public.social_post_like
      add constraint social_post_like_post_fkey
      foreign key (post_id)
      references public.social_post(id)
      on update cascade
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'social_post_like_user_fkey'
      and conrelid = 'public.social_post_like'::regclass
  ) then
    alter table public.social_post_like
      add constraint social_post_like_user_fkey
      foreign key (user_id)
      references public.profiles(id)
      on update cascade
      on delete cascade;
  end if;
end $$;

create index if not exists social_post_author_created_idx
  on public.social_post (author_id, created_at desc)
  where deleted_at is null;

create index if not exists social_post_feed_created_idx
  on public.social_post (created_at desc, id desc)
  where deleted_at is null;

create index if not exists social_post_workout_source_idx
  on public.social_post (source_workout_type_instance_id);

create index if not exists social_post_like_user_idx
  on public.social_post_like (user_id, created_at desc);

alter table public.social_post enable row level security;
alter table public.social_post_like enable row level security;

grant select, insert, update, delete on public.social_post to authenticated;
grant select, insert, delete on public.social_post_like to authenticated;

drop policy if exists "Social posts are viewable by owners and followers"
  on public.social_post;

create policy "Social posts are viewable by owners and followers"
on public.social_post
for select
to authenticated
using (
  (select auth.uid()) is not null
  and (
    author_id = (select auth.uid())
    or (
      deleted_at is null
      and exists (
        select 1
        from public.user_follows follow
        where follow.follower_id = (select auth.uid())
          and follow.following_id = public.social_post.author_id
      )
    )
  )
);

drop policy if exists "Users can insert their own social posts"
  on public.social_post;

create policy "Users can insert their own social posts"
on public.social_post
for insert
to authenticated
with check (
  (select auth.uid()) = author_id
  and deleted_at is null
  and exists (
    select 1
    from public.workout_type_instance workout
    where workout.id = public.social_post.source_workout_type_instance_id
      and workout.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can update their own social posts"
  on public.social_post;

create policy "Users can update their own social posts"
on public.social_post
for update
to authenticated
using ((select auth.uid()) = author_id)
with check (
  (select auth.uid()) = author_id
  and exists (
    select 1
    from public.workout_type_instance workout
    where workout.id = public.social_post.source_workout_type_instance_id
      and workout.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can delete their own social posts"
  on public.social_post;

create policy "Users can delete their own social posts"
on public.social_post
for delete
to authenticated
using ((select auth.uid()) = author_id);

drop policy if exists "Social post likes are viewable with visible posts"
  on public.social_post_like;

create policy "Social post likes are viewable with visible posts"
on public.social_post_like
for select
to authenticated
using (
  exists (
    select 1
    from public.social_post post
    where post.id = public.social_post_like.post_id
      and post.deleted_at is null
      and (
        post.author_id = (select auth.uid())
        or exists (
          select 1
          from public.user_follows follow
          where follow.follower_id = (select auth.uid())
            and follow.following_id = post.author_id
        )
      )
  )
);

drop policy if exists "Users can like visible social posts"
  on public.social_post_like;

create policy "Users can like visible social posts"
on public.social_post_like
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.social_post post
    where post.id = public.social_post_like.post_id
      and post.deleted_at is null
      and (
        post.author_id = (select auth.uid())
        or exists (
          select 1
          from public.user_follows follow
          where follow.follower_id = (select auth.uid())
            and follow.following_id = post.author_id
        )
      )
  )
);

drop policy if exists "Users can remove their own social post likes"
  on public.social_post_like;

create policy "Users can remove their own social post likes"
on public.social_post_like
for delete
to authenticated
using ((select auth.uid()) = user_id);

commit;

-- Expected payload shape for workout_summary posts:
--
-- {
--   "durationSeconds": 3120,
--   "setsCount": 18,
--   "exerciseCount": 5,
--   "topSets": [
--     { "exerciseName": "Bench Press", "reps": 3, "weight": 100, "unit": "kg" }
--   ],
--   "personalRecords": [
--     { "exerciseName": "Bench Press", "recordType": "weight", "value": 100, "unit": "kg" }
--   ]
-- }
