-- Adds sickness periods used by FitApp clients.
-- Run this against the Supabase project before shipping clients that sync
-- Sickness records.

create table if not exists public."Sickness" (
  sickness_id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date,
  sickness_type text,
  note text,
  deleted_at timestamptz,

  constraint sickness_date_range_check
    check (end_date is null or end_date >= start_date)
);

create index if not exists sickness_user_date_idx
  on public."Sickness" (user_id, start_date, end_date);

alter table public."Sickness" enable row level security;

drop policy if exists "Users can view their own sickness records"
  on public."Sickness";
create policy "Users can view their own sickness records"
  on public."Sickness"
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own sickness records"
  on public."Sickness";
create policy "Users can insert their own sickness records"
  on public."Sickness"
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own sickness records"
  on public."Sickness";
create policy "Users can update their own sickness records"
  on public."Sickness"
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own sickness records"
  on public."Sickness";
create policy "Users can delete their own sickness records"
  on public."Sickness"
  for delete
  to authenticated
  using (auth.uid() = user_id);
