-- Adds body map region metadata for exercise catalog muscle highlights.
--
-- Source of truth remains:
--   public."Exercise" -> public."Muscle_Activation" -> public."Muscle"
--
-- These tables only describe how concrete muscles map to visual body-map
-- regions. The app can derive primary/secondary highlights from
-- Muscle_Activation.activation_level.

begin;

create table if not exists public.body_map_region (
  id bigint generated by default as identity not null,
  region_key text not null,
  body_view text not null,
  body_section text not null,
  name text not null,
  constraint body_map_region_pkey primary key (id),
  constraint body_map_region_view_key_unique unique (body_view, region_key),
  constraint body_map_region_key_not_blank check (btrim(region_key) <> ''),
  constraint body_map_region_name_not_blank check (btrim(name) <> ''),
  constraint body_map_region_body_view_valid
    check (body_view in ('front', 'back')),
  constraint body_map_region_body_section_valid
    check (body_section in ('upper', 'lower'))
);

alter table public.body_map_region
  add column if not exists region_key text;

alter table public.body_map_region
  add column if not exists body_view text;

alter table public.body_map_region
  add column if not exists body_section text;

alter table public.body_map_region
  add column if not exists name text;

update public.body_map_region
set
  region_key = lower(regexp_replace(btrim(region_key), '[^a-zA-Z0-9]+', '_', 'g')),
  body_view = lower(btrim(body_view)),
  name = btrim(name)
where region_key is not null
  and body_view is not null
  and name is not null;

update public.body_map_region
set body_section = lower(btrim(body_section))
where body_section is not null;

delete from public.body_map_region
where btrim(coalesce(region_key, '')) = ''
   or btrim(coalesce(body_view, '')) not in ('front', 'back')
   or btrim(coalesce(name, '')) = '';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_view_key_unique'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_view_key_unique
      unique (body_view, region_key);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_key_not_blank'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_key_not_blank
      check (btrim(region_key) <> '');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_name_not_blank'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_name_not_blank
      check (btrim(name) <> '');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_body_view_valid'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_body_view_valid
      check (body_view in ('front', 'back'));
  end if;
end $$;

with seed_regions(body_view, body_section, region_key, name) as (
  values
    ('front', 'upper', 'abs', 'Abs'),
    ('front', 'lower', 'adductors', 'Adductors'),
    ('front', 'upper', 'biceps', 'Biceps'),
    ('front', 'upper', 'forearms', 'Forearms'),
    ('front', 'upper', 'front_delts', 'Front delts'),
    ('front', 'upper', 'obliques', 'Obliques'),
    ('front', 'upper', 'pecs', 'Pecs'),
    ('front', 'lower', 'quads', 'Quads'),
    ('front', 'upper', 'side_delts', 'Side delts'),
    ('front', 'upper', 'upper_traps', 'Upper traps'),
    ('back', 'lower', 'adductors', 'Adductors'),
    ('back', 'lower', 'calves', 'Calves'),
    ('back', 'lower', 'glutes', 'Glutes'),
    ('back', 'lower', 'hamstrings', 'Hamstrings'),
    ('back', 'upper', 'infraspinatus', 'Infraspinatus'),
    ('back', 'upper', 'lats', 'Lats'),
    ('back', 'upper', 'lower_back', 'Lower back'),
    ('back', 'upper', 'rear_delts', 'Rear delts'),
    ('back', 'upper', 'side_delts', 'Side delts'),
    ('back', 'upper', 'teres_major', 'Teres major'),
    ('back', 'upper', 'teres_minor', 'Teres minor'),
    ('back', 'upper', 'triceps', 'Triceps'),
    ('back', 'upper', 'upper_traps', 'Upper traps')
)
insert into public.body_map_region (body_view, body_section, region_key, name)
select
  seed_regions.body_view,
  seed_regions.body_section,
  seed_regions.region_key,
  seed_regions.name
from seed_regions
on conflict (body_view, region_key) do update
set
  body_section = excluded.body_section,
  name = excluded.name;

-- Existing custom regions that are not covered by the seed need a valid value
-- before the column can be made required. Review and correct these manually if
-- "upper" is not the right section.
update public.body_map_region
set body_section = 'upper'
where body_section is null
   or btrim(body_section) not in ('upper', 'lower');

alter table public.body_map_region
  alter column body_section set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'body_map_region_body_section_valid'
      and conrelid = 'public.body_map_region'::regclass
  ) then
    alter table public.body_map_region
      add constraint body_map_region_body_section_valid
      check (body_section in ('upper', 'lower'));
  end if;
end $$;

create table if not exists public.muscle_body_map_region (
  muscle_id bigint not null,
  body_map_region_id bigint not null,
  constraint muscle_body_map_region_pkey
    primary key (muscle_id, body_map_region_id),
  constraint muscle_body_map_region_muscle_fkey
    foreign key (muscle_id)
    references public."Muscle"(id)
    on update cascade
    on delete cascade,
  constraint muscle_body_map_region_region_fkey
    foreign key (body_map_region_id)
    references public.body_map_region(id)
    on update cascade
    on delete cascade
);

alter table public.muscle_body_map_region
  add column if not exists muscle_id bigint;

alter table public.muscle_body_map_region
  add column if not exists body_map_region_id bigint;

delete from public.muscle_body_map_region
where muscle_id is null
   or body_map_region_id is null;

alter table public.muscle_body_map_region
  alter column muscle_id set not null;

alter table public.muscle_body_map_region
  alter column body_map_region_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'muscle_body_map_region_pkey'
      and conrelid = 'public.muscle_body_map_region'::regclass
  ) then
    alter table public.muscle_body_map_region
      add constraint muscle_body_map_region_pkey
      primary key (muscle_id, body_map_region_id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'muscle_body_map_region_muscle_fkey'
      and conrelid = 'public.muscle_body_map_region'::regclass
  ) then
    alter table public.muscle_body_map_region
      add constraint muscle_body_map_region_muscle_fkey
      foreign key (muscle_id)
      references public."Muscle"(id)
      on update cascade
      on delete cascade;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'muscle_body_map_region_region_fkey'
      and conrelid = 'public.muscle_body_map_region'::regclass
  ) then
    alter table public.muscle_body_map_region
      add constraint muscle_body_map_region_region_fkey
      foreign key (body_map_region_id)
      references public.body_map_region(id)
      on update cascade
      on delete cascade;
  end if;
end $$;

create index if not exists muscle_body_map_region_region_id_idx
  on public.muscle_body_map_region (body_map_region_id);

alter table public.body_map_region enable row level security;
alter table public.muscle_body_map_region enable row level security;

grant select on public.body_map_region to authenticated;
grant select on public.muscle_body_map_region to authenticated;

drop policy if exists "Body map regions are viewable by authenticated users"
  on public.body_map_region;

create policy "Body map regions are viewable by authenticated users"
on public.body_map_region
for select
to authenticated
using (true);

drop policy if exists "Muscle body map regions are viewable by authenticated users"
  on public.muscle_body_map_region;

create policy "Muscle body map regions are viewable by authenticated users"
on public.muscle_body_map_region
for select
to authenticated
using (true);

-- Default mappings for the current public."Muscle" catalog.
-- Unmapped for now because no matching body-map region exists yet:
-- Serratus Anterior, Tibialis Anterior, Rhomboideus.
with seed_mappings(muscle_name, body_view, region_key) as (
  values
    ('Pectoralis Major', 'front', 'pecs'),
    ('Pectoralis Minor', 'front', 'pecs'),
    ('Front Deltoid', 'front', 'front_delts'),
    ('Lateral Deltoid', 'front', 'side_delts'),
    ('Lateral Deltoid', 'back', 'side_delts'),
    ('Rear Deltoid', 'back', 'rear_delts'),
    ('Biceps Brachii', 'front', 'biceps'),
    ('Rectus Abdominis', 'front', 'abs'),
    ('Abdominal External Oblique', 'front', 'obliques'),
    ('Rectus Femoris', 'front', 'quads'),
    ('Vastus Lateralis', 'front', 'quads'),
    ('Vastus Medialis', 'front', 'quads'),
    ('Soleus', 'back', 'calves'),
    ('Gastrocnemius', 'back', 'calves'),
    ('Biceps Femoris', 'back', 'hamstrings'),
    ('Semitendinosus', 'back', 'hamstrings'),
    ('Semimembranosus', 'back', 'hamstrings'),
    ('Gluteus Maximus', 'back', 'glutes'),
    ('Gluteus Medius', 'back', 'glutes'),
    ('Latissimus Dorsi', 'back', 'lats'),
    ('Erector Spinae', 'back', 'lower_back'),
    ('Trapezius', 'front', 'upper_traps'),
    ('Trapezius', 'back', 'upper_traps'),
    ('Triceps Brachii', 'back', 'triceps')
)
insert into public.muscle_body_map_region (muscle_id, body_map_region_id)
select
  "Muscle".id,
  body_map_region.id
from seed_mappings
join public."Muscle"
  on lower(btrim("Muscle".name)) = lower(btrim(seed_mappings.muscle_name))
join public.body_map_region
  on body_map_region.body_view = seed_mappings.body_view
 and body_map_region.region_key = seed_mappings.region_key
on conflict (muscle_id, body_map_region_id) do nothing;

commit;
