-- Adds exercise catalog grouping metadata.
--
-- This keeps concrete muscles in public."Muscle" and maps those muscles to
-- broader UI groups such as Push, Pull, Legs, Core, and Mobility. The app then
-- derives an exercise's group from its Muscle_Activation rows instead of
-- storing a separate hardcoded group directly on each exercise.

create table if not exists public.muscle_group (
  id bigint generated by default as identity not null,
  group_key text not null,
  name text not null,
  display_order integer not null default 0,
  is_active boolean not null default true,
  constraint muscle_group_pkey primary key (id),
  constraint muscle_group_group_key_key unique (group_key),
  constraint muscle_group_group_key_not_blank check (btrim(group_key) <> ''),
  constraint muscle_group_name_not_blank check (btrim(name) <> '')
);

alter table public.muscle_group
  add column if not exists group_key text;

alter table public.muscle_group
  add column if not exists name text;

alter table public.muscle_group
  add column if not exists display_order integer not null default 0;

alter table public.muscle_group
  add column if not exists is_active boolean not null default true;

update public.muscle_group
set
  group_key = lower(regexp_replace(btrim(group_key), '[^a-zA-Z0-9]+', '-', 'g')),
  name = btrim(name)
where group_key is not null
  and name is not null;

delete from public.muscle_group
where btrim(coalesce(group_key, '')) = ''
   or btrim(coalesce(name, '')) = '';

with seed_groups(group_key, name, display_order, is_active) as (
  values
    ('push', 'Push', 10, true),
    ('pull', 'Pull', 20, true),
    ('legs', 'Legs', 30, true),
    ('core', 'Core', 40, true),
    ('mobility', 'Mobility', 50, true)
)
insert into public.muscle_group (group_key, name, display_order, is_active)
select
  seed_groups.group_key,
  seed_groups.name,
  seed_groups.display_order,
  seed_groups.is_active
from seed_groups
on conflict (group_key) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = excluded.is_active;

do $$
begin
  if to_regclass('public.muscle_group_assignment') is null
    and to_regclass('public.muscle_group_muscle') is not null then
    alter table public.muscle_group_muscle rename to muscle_group_assignment;
  end if;
end $$;

create table if not exists public.muscle_group_assignment (
  muscle_group_id bigint not null,
  muscle_id bigint not null,
  constraint muscle_group_assignment_pkey
    primary key (muscle_group_id, muscle_id),
  constraint muscle_group_assignment_group_fkey
    foreign key (muscle_group_id)
    references public.muscle_group(id)
    on update cascade
    on delete cascade,
  constraint muscle_group_assignment_muscle_fkey
    foreign key (muscle_id)
    references public."Muscle"(id)
    on update cascade
    on delete cascade
);

do $$
begin
  if exists (
    select 1
    from pg_constraint
    where conrelid = 'public.muscle_group_assignment'::regclass
      and conname = 'muscle_group_muscle_pkey'
  ) and not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.muscle_group_assignment'::regclass
      and conname = 'muscle_group_assignment_pkey'
  ) then
    alter table public.muscle_group_assignment
      rename constraint muscle_group_muscle_pkey to muscle_group_assignment_pkey;
  end if;

  if exists (
    select 1
    from pg_constraint
    where conrelid = 'public.muscle_group_assignment'::regclass
      and conname = 'muscle_group_muscle_group_fkey'
  ) and not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.muscle_group_assignment'::regclass
      and conname = 'muscle_group_assignment_group_fkey'
  ) then
    alter table public.muscle_group_assignment
      rename constraint muscle_group_muscle_group_fkey
      to muscle_group_assignment_group_fkey;
  end if;

  if exists (
    select 1
    from pg_constraint
    where conrelid = 'public.muscle_group_assignment'::regclass
      and conname = 'muscle_group_muscle_muscle_fkey'
  ) and not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.muscle_group_assignment'::regclass
      and conname = 'muscle_group_assignment_muscle_fkey'
  ) then
    alter table public.muscle_group_assignment
      rename constraint muscle_group_muscle_muscle_fkey
      to muscle_group_assignment_muscle_fkey;
  end if;
end $$;

create index if not exists muscle_group_active_order_idx
  on public.muscle_group (is_active, display_order, name);

drop index if exists public.muscle_group_muscle_muscle_id_idx;

create index if not exists muscle_group_assignment_muscle_id_idx
  on public.muscle_group_assignment (muscle_id);

-- Optional seed examples. These inserts only apply when the listed muscle names
-- already exist in public."Muscle"; adjust the names to match the catalog.
with seed_group_assignments(group_key, muscle_name) as (
  values
    ('push', 'Chest'),
    ('push', 'Pectoralis Major'),
    ('push', 'Triceps'),
    ('push', 'Anterior Deltoid'),
    ('pull', 'Back'),
    ('pull', 'Latissimus Dorsi'),
    ('pull', 'Biceps'),
    ('pull', 'Rear Deltoid'),
    ('legs', 'Quadriceps'),
    ('legs', 'Hamstrings'),
    ('legs', 'Glutes'),
    ('legs', 'Calves'),
    ('core', 'Abs'),
    ('core', 'Abdominals'),
    ('core', 'Obliques'),
    ('mobility', 'Rotator Cuff')
)
insert into public.muscle_group_assignment (muscle_group_id, muscle_id)
select
  muscle_group.id,
  "Muscle".id
from seed_group_assignments
join public.muscle_group
  on muscle_group.group_key = seed_group_assignments.group_key
join public."Muscle"
  on lower("Muscle".name) = lower(seed_group_assignments.muscle_name)
on conflict (muscle_group_id, muscle_id) do nothing;

alter table public.muscle_group enable row level security;
alter table public.muscle_group_assignment enable row level security;

drop policy if exists "Muscle groups are viewable by authenticated users"
  on public.muscle_group;

create policy "Muscle groups are viewable by authenticated users"
on public.muscle_group
for select
to authenticated
using (true);

drop policy if exists "Muscle group mappings are viewable by authenticated users"
  on public.muscle_group_assignment;

drop policy if exists "Muscle group assignments are viewable by authenticated users"
  on public.muscle_group_assignment;

create policy "Muscle group assignments are viewable by authenticated users"
on public.muscle_group_assignment
for select
to authenticated
using (true);
