-- What was playing during a workout, for the Friends activity tiles.
--
-- Run after:
--   supabase/migrations/20260917120000_gyms-and-lift-verification.sql
--
-- The client writes a row every time the track changes while a workout is
-- running, and only when the user has connected a music provider and switched
-- "Share music with friends" on. Followers read the newest row for a live
-- workout ("playing") or a finished one ("last"). Switching sharing off deletes
-- the user's rows, so nothing lingers - the toggle is stored in profile_private
-- for the settings screen, not consulted by a policy: a policy that reads
-- another user's private row would silently see nothing (src/AGENTS.md).

begin;

alter table public.profile_private
  add column if not exists share_music_with_friends boolean not null default false;

create table if not exists public.workout_music (
  id                       bigint generated by default as identity primary key,
  user_id                  uuid not null references public.profiles(id) on delete cascade,
  workout_type_instance_id bigint not null references public.workout_type_instance(id) on delete cascade,
  provider                 text not null check (provider in ('spotify', 'apple_music')),
  track                    text not null,
  artist                   text,
  art_url                  text,
  track_uri                text,
  played_at                timestamptz not null default timezone('utc', now()),
  created_at               timestamptz not null default timezone('utc', now())
);

create index if not exists workout_music_workout_played_idx
  on public.workout_music (workout_type_instance_id, played_at desc);
create index if not exists workout_music_user_idx
  on public.workout_music (user_id, played_at desc);

alter table public.workout_music enable row level security;

revoke all on public.workout_music from anon, authenticated;
grant select, insert, delete on public.workout_music to authenticated;
-- The poller touches played_at on the newest row while the same track keeps
-- playing, so "playing" can be read as "a row under 90 seconds old" without a
-- new row every poll.
grant update (played_at, art_url) on public.workout_music to authenticated;

-- Followers of the owner, and the owner. Reading through user_follows is what
-- makes a block cut this off for free, like every other follower-visible thing.
drop policy if exists "Followers can view workout music" on public.workout_music;
create policy "Followers can view workout music"
on public.workout_music
for select
to authenticated
using (
  (select auth.uid()) = user_id
  or exists (
    select 1
    from public.user_follows follow
    where follow.follower_id = (select auth.uid())
      and follow.following_id = public.workout_music.user_id
  )
);

drop policy if exists "Users can record their own workout music" on public.workout_music;
create policy "Users can record their own workout music"
on public.workout_music
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1
    from public.workout_type_instance workout
    where workout.id = public.workout_music.workout_type_instance_id
      and workout.user_id = (select auth.uid())
  )
);

drop policy if exists "Users can touch their own workout music" on public.workout_music;
create policy "Users can touch their own workout music"
on public.workout_music
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own workout music" on public.workout_music;
create policy "Users can delete their own workout music"
on public.workout_music
for delete
to authenticated
using ((select auth.uid()) = user_id);

commit;
