-- Centres, workout -> centre matching, per-centre lift leaderboards and lift
-- video verification.
--
-- Run after:
--   supabase/migrations/20260916210000_opt-in-column-defaults.sql
--
-- A centre is a public fitness centre with a chain, a name, an address,
-- coordinates and a hero image. The rows come from `npm run gyms:import`, which
-- reads data/gyms/ and runs with the service role - app users only read them.
--
-- A workout belongs to a centre when the client matched its start position to
-- one (match_gym). The best set per exercise of a finished strength workout in
-- a centre lands in gym_lift, one row per (user, centre, exercise), and that is
-- what the leaderboards rank. Every leaderboard read goes through a security
-- definer function below rather than a table policy, for two reasons:
--   * ranking needs other people's profiles, which public.profiles no longer
--     answers for strangers, and
--   * blocks have to be filtered, and src/AGENTS.md is explicit that a block
--     check in an RLS expression silently passes - it has to be a security
--     definer function.
-- gym_lift therefore has an own-rows-only select policy; the functions are the
-- public surface.

begin;

create schema if not exists private;

/* ------------------------------------------------------------------ gym -- */

create table if not exists public.gym (
  id             bigint generated by default as identity primary key,
  chain          text not null,
  name           text not null,
  short_name     text not null,
  address        text,
  postal_code    text,
  city           text,
  latitude       double precision not null,
  longitude      double precision not null,
  match_radius_m integer not null default 120,
  image_url      text,
  source_url     text,
  membership_url text,
  external_id    text,
  facilities     text[] not null default '{}',
  opening_hours  jsonb,
  description    text,
  is_public      boolean not null default true,
  created_at     timestamptz not null default timezone('utc', now()),
  updated_at     timestamptz not null default timezone('utc', now())
);

alter table public.gym add column if not exists postal_code text;
alter table public.gym add column if not exists membership_url text;
alter table public.gym add column if not exists external_id text;
alter table public.gym add column if not exists facilities text[] not null default '{}';
alter table public.gym add column if not exists opening_hours jsonb;
alter table public.gym add column if not exists description text;

create unique index if not exists gym_chain_name_key on public.gym (chain, name);
create index if not exists gym_location_idx on public.gym (latitude, longitude);

create or replace function private.set_row_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_gym_updated_at on public.gym;
create trigger set_gym_updated_at
before update on public.gym
for each row execute function private.set_row_updated_at();

alter table public.gym enable row level security;

revoke all on public.gym from anon, authenticated;
grant select on public.gym to authenticated;

drop policy if exists "Gyms are viewable by authenticated users" on public.gym;
create policy "Gyms are viewable by authenticated users"
on public.gym
for select
to authenticated
using (is_public);

/* ------------------------------------------- workout -> centre matching -- */

alter table public.workout_type_instance
  add column if not exists gym_id bigint references public.gym(id) on delete set null;
alter table public.workout_type_instance
  add column if not exists start_latitude double precision;
alter table public.workout_type_instance
  add column if not exists start_longitude double precision;

create index if not exists workout_type_instance_gym_idx
  on public.workout_type_instance (gym_id, user_id)
  where gym_id is not null;

/* --------------------------------------------------- the user's centre -- */

alter table public.profile_private
  add column if not exists home_gym_id bigint references public.gym(id) on delete set null;

/* ------------------------------------------------------------- gym_lift -- */

create table if not exists public.gym_lift (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null references public.profiles(id) on delete cascade,
  gym_id             bigint not null references public.gym(id) on delete cascade,
  exercise_id        bigint not null,
  exercise_name      text not null,
  weight_kg          numeric(6,2) not null,
  reps               integer not null,
  set_sync_id        uuid,
  performed_at       timestamptz not null,
  bodyweight_kg      numeric(5,2),
  previous_weight_kg numeric(6,2),
  video_path         text,
  video_status       text not null default 'none'
                     check (video_status in ('none', 'pending', 'verified', 'rejected')),
  approvals          integer not null default 0,
  rejections         integer not null default 0,
  created_at         timestamptz not null default timezone('utc', now()),
  updated_at         timestamptz not null default timezone('utc', now()),
  unique (user_id, gym_id, exercise_id)
);

alter table public.gym_lift add column if not exists previous_weight_kg numeric(6,2);

create index if not exists gym_lift_rank_idx
  on public.gym_lift (gym_id, exercise_id, weight_kg desc);
create index if not exists gym_lift_national_idx
  on public.gym_lift (exercise_id, weight_kg desc)
  where video_status = 'verified';
create index if not exists gym_lift_user_idx
  on public.gym_lift (user_id);

-- The status columns belong to the vote trigger. A client insert cannot set
-- them, whatever the payload says, and an update can only touch the columns
-- granted below.
create or replace function private.gym_lift_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.approvals := 0;
  new.rejections := 0;
  new.previous_weight_kg := null;
  new.video_status := case when new.video_path is null then 'none' else 'pending' end;
  new.created_at := timezone('utc', now());
  new.updated_at := new.created_at;
  return new;
end;
$$;

drop trigger if exists gym_lift_before_insert on public.gym_lift;
create trigger gym_lift_before_insert
before insert on public.gym_lift
for each row execute function private.gym_lift_before_insert();

-- A heavier lift replaces the row and the video no longer shows the lift being
-- ranked, so it goes. Same weight keeps the video and its votes. A new video
-- resets the votes. Anything else leaves the status columns alone - unless the
-- update is the recount itself, which announces itself through a setting.
create or replace function private.gym_lift_before_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if current_setting('fitven.gym_lift_recount', true) = 'on' then
    new.updated_at := timezone('utc', now());
    return new;
  end if;

  -- The votes go with the video. Deleting them fires the recount trigger,
  -- which would update this very row from inside its own BEFORE trigger -
  -- Postgres refuses that ("tuple to be updated was already modified") - so
  -- the recount is told to stand down; the values are set right here anyway.
  if new.weight_kg <> old.weight_kg then
    new.previous_weight_kg := old.weight_kg;
    new.video_path := null;
    new.video_status := 'none';
    new.approvals := 0;
    new.rejections := 0;
    perform set_config('fitven.gym_lift_skip_recount', 'on', true);
    delete from public.gym_lift_vote where lift_id = old.id;
    perform set_config('fitven.gym_lift_skip_recount', 'off', true);
  elsif new.video_path is distinct from old.video_path then
    new.video_status := case when new.video_path is null then 'none' else 'pending' end;
    new.approvals := 0;
    new.rejections := 0;
    perform set_config('fitven.gym_lift_skip_recount', 'on', true);
    delete from public.gym_lift_vote where lift_id = old.id;
    perform set_config('fitven.gym_lift_skip_recount', 'off', true);
  else
    new.video_status := old.video_status;
    new.approvals := old.approvals;
    new.rejections := old.rejections;
    new.previous_weight_kg := old.previous_weight_kg;
  end if;

  new.user_id := old.user_id;
  new.gym_id := old.gym_id;
  new.exercise_id := old.exercise_id;
  new.created_at := old.created_at;
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists gym_lift_before_update on public.gym_lift;
create trigger gym_lift_before_update
before update on public.gym_lift
for each row execute function private.gym_lift_before_update();

alter table public.gym_lift enable row level security;

revoke all on public.gym_lift from anon, authenticated;
grant select, insert, delete on public.gym_lift to authenticated;
-- The identity columns are in the list because PostgREST's upsert writes
-- every payload column in its ON CONFLICT DO UPDATE; the before-update
-- trigger puts them back to the old values regardless. The status columns are
-- deliberately not here.
grant update (user_id, gym_id, exercise_id, exercise_name, weight_kg, reps, set_sync_id, performed_at, bodyweight_kg, video_path, updated_at)
  on public.gym_lift to authenticated;

drop policy if exists "Users can view their own lifts" on public.gym_lift;
create policy "Users can view their own lifts"
on public.gym_lift
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own lifts" on public.gym_lift;
create policy "Users can insert their own lifts"
on public.gym_lift
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own lifts" on public.gym_lift;
create policy "Users can update their own lifts"
on public.gym_lift
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own lifts" on public.gym_lift;
create policy "Users can delete their own lifts"
on public.gym_lift
for delete
to authenticated
using ((select auth.uid()) = user_id);

/* -------------------------------------------------------- gym_lift_vote -- */

create table if not exists public.gym_lift_vote (
  lift_id    bigint not null references public.gym_lift(id) on delete cascade,
  voter_id   uuid not null references public.profiles(id) on delete cascade,
  approve    boolean not null,
  reason     text check (reason is null or reason in ('depth', 'lockout', 'assist', 'weight', 'other')),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (lift_id, voter_id)
);

create index if not exists gym_lift_vote_voter_idx on public.gym_lift_vote (voter_id);

create or replace function private.blocked_between(left_id uuid, right_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_blocks block
    where (block.blocker_id = left_id and block.blocked_id = right_id)
       or (block.blocker_id = right_id and block.blocked_id = left_id)
  );
$$;

create or replace function private.trains_at_gym(member_id uuid, target_gym_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workout_type_instance workout
    where workout.user_id = member_id
      and workout.gym_id = target_gym_id
      and workout.done = true
      and workout.deleted_at is null
      and workout.date::date >= current_date - 90
  );
$$;

-- Who may vote: not the lifter, somebody who trains at the same centre, and
-- nobody on either side of a block. Security definer because the lift row and
-- the other person's workouts are not the voter's to read.
create or replace function private.gym_lift_vote_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  lift public.gym_lift%rowtype;
begin
  select * into lift from public.gym_lift where id = new.lift_id;

  if not found then
    raise exception 'That lift no longer exists.' using errcode = '23503';
  end if;

  if lift.user_id = new.voter_id then
    raise exception 'You cannot vote on your own lift.' using errcode = '42501';
  end if;

  if lift.video_path is null then
    raise exception 'This lift has no video to review.' using errcode = '23514';
  end if;

  if private.blocked_between(lift.user_id, new.voter_id) then
    raise exception 'That lift is not available.' using errcode = '42501';
  end if;

  if not private.trains_at_gym(new.voter_id, lift.gym_id) then
    raise exception 'Only people who train at this centre can vote on its lifts.' using errcode = '42501';
  end if;

  if new.approve then
    new.reason := null;
  elsif new.reason is null then
    new.reason := 'other';
  end if;

  new.created_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists gym_lift_vote_before_insert on public.gym_lift_vote;
create trigger gym_lift_vote_before_insert
before insert on public.gym_lift_vote
for each row execute function private.gym_lift_vote_before_insert();

-- Recount after every vote. Two rejections beat any number of approvals.
create or replace function private.gym_lift_vote_recount()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_lift_id bigint := coalesce(new.lift_id, old.lift_id);
  approval_count integer;
  rejection_count integer;
begin
  if current_setting('fitven.gym_lift_skip_recount', true) = 'on' then
    return null;
  end if;

  select
    count(*) filter (where vote.approve),
    count(*) filter (where not vote.approve)
  into approval_count, rejection_count
  from public.gym_lift_vote vote
  where vote.lift_id = target_lift_id;

  perform set_config('fitven.gym_lift_recount', 'on', true);

  update public.gym_lift
  set approvals = approval_count,
      rejections = rejection_count,
      video_status = case
        when video_path is null then 'none'
        when rejection_count >= 2 then 'rejected'
        when approval_count >= 3 then 'verified'
        else 'pending'
      end
  where id = target_lift_id;

  perform set_config('fitven.gym_lift_recount', 'off', true);

  return null;
end;
$$;

drop trigger if exists gym_lift_vote_recount on public.gym_lift_vote;
create trigger gym_lift_vote_recount
after insert or delete on public.gym_lift_vote
for each row execute function private.gym_lift_vote_recount();

alter table public.gym_lift_vote enable row level security;

revoke all on public.gym_lift_vote from anon, authenticated;
grant select, insert, delete on public.gym_lift_vote to authenticated;

drop policy if exists "Users can view their own votes" on public.gym_lift_vote;
create policy "Users can view their own votes"
on public.gym_lift_vote
for select
to authenticated
using ((select auth.uid()) = voter_id);

drop policy if exists "Users can vote from their own account" on public.gym_lift_vote;
create policy "Users can vote from their own account"
on public.gym_lift_vote
for insert
to authenticated
with check ((select auth.uid()) = voter_id);

drop policy if exists "Users can withdraw their own votes" on public.gym_lift_vote;
create policy "Users can withdraw their own votes"
on public.gym_lift_vote
for delete
to authenticated
using ((select auth.uid()) = voter_id);

/* -------------------------------------------------------------- storage -- */

-- Lift videos: private, readable by anyone signed in (a leaderboard is public
-- inside the app), writable only inside your own folder. 50 MB is the ceiling
-- the client compresses towards.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lift-videos', 'lift-videos', false, 52428800, array['video/mp4', 'video/quicktime'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Authenticated users can read lift videos" on storage.objects;
create policy "Authenticated users can read lift videos"
on storage.objects
for select
to authenticated
using (bucket_id = 'lift-videos');

drop policy if exists "Users can upload their own lift videos" on storage.objects;
create policy "Users can upload their own lift videos"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'lift-videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users can replace their own lift videos" on storage.objects;
create policy "Users can replace their own lift videos"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'lift-videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users can delete their own lift videos" on storage.objects;
create policy "Users can delete their own lift videos"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'lift-videos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- Centre hero images: marketing photographs scraped from the chains' public
-- sites. Public on purpose - nothing personal, and a public URL needs no
-- signing on every render. Written by the import script with the service role.
insert into storage.buckets (id, name, public)
values ('gym-images', 'gym-images', true)
on conflict (id) do update set public = true;

/* -------------------------------------------------------------- helpers -- */

-- Bench press, squat and deadlift, in that order, by name in the shared
-- catalog. The names are the ones src/Database/schema/weightlifting.js seeds.
create or replace function private.featured_exercises()
returns table (exercise_id bigint, exercise_name text, sort_order integer)
language sql
stable
security definer
set search_path = ''
as $$
  select
    exercise.id::bigint,
    exercise.name::text,
    array_position(array['bench press', 'squat', 'deadlift'], lower(exercise.name))
  from public."Exercise" exercise
  where lower(exercise.name) in ('bench press', 'squat', 'deadlift')
  order by 3;
$$;

create or replace function private.home_gym_id_for(member_id uuid)
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select settings.home_gym_id
      from public.profile_private settings
      where settings.user_id = member_id
    ),
    (
      select mode() within group (order by workout.gym_id)
      from public.workout_type_instance workout
      where workout.user_id = member_id
        and workout.gym_id is not null
        and workout.done = true
        and workout.deleted_at is null
        and workout.date::date >= current_date - 90
    )
  );
$$;

create or replace function private.gym_member_count(target_gym_id bigint)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select count(distinct workout.user_id)::integer
  from public.workout_type_instance workout
  where workout.gym_id = target_gym_id
    and workout.done = true
    and workout.deleted_at is null
    and workout.date::date >= current_date - 90;
$$;

create or replace function private.gym_followed_member_count(target_gym_id bigint, viewer_id uuid)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select count(distinct workout.user_id)::integer
  from public.workout_type_instance workout
  join public.user_follows follow
    on follow.follower_id = viewer_id
   and follow.following_id = workout.user_id
  where workout.gym_id = target_gym_id
    and workout.done = true
    and workout.deleted_at is null
    and workout.date::date >= current_date - 90;
$$;

create or replace function private.gym_summary(target_gym_id bigint, viewer_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', gym.id,
    'chain', gym.chain,
    'name', gym.name,
    'short_name', gym.short_name,
    'address', gym.address,
    'city', gym.city,
    'latitude', gym.latitude,
    'longitude', gym.longitude,
    'image_url', gym.image_url,
    'member_count', private.gym_member_count(gym.id),
    'followed_member_count', private.gym_followed_member_count(gym.id, viewer_id),
    'is_home_gym', gym.id = private.home_gym_id_for(viewer_id)
  )
  from public.gym gym
  where gym.id = target_gym_id
    and gym.is_public;
$$;

/* ------------------------------------------------------------ match_gym -- */

-- Nearest public centre within its own match radius, or nothing. The
-- bounding box is what the (latitude, longitude) index answers; the haversine
-- runs on those few rows.
create or replace function public.match_gym(lat double precision, lng double precision)
returns setof public.gym
language sql
stable
security definer
set search_path = ''
as $$
  with candidates as (
    select
      gym.*,
      2 * 6371000 * asin(sqrt(
        power(sin(radians(gym.latitude - lat) / 2), 2)
        + cos(radians(lat)) * cos(radians(gym.latitude))
          * power(sin(radians(gym.longitude - lng) / 2), 2)
      )) as distance_m
    from public.gym gym
    where gym.is_public
      and gym.latitude between lat - 0.01 and lat + 0.01
      and gym.longitude between lng - 0.02 and lng + 0.02
  )
  select gym.*
  from public.gym gym
  where gym.id = (
    select candidates.id
    from candidates
    where candidates.distance_m <= candidates.match_radius_m
    order by candidates.distance_m asc
    limit 1
  );
$$;

revoke all on function public.match_gym(double precision, double precision) from public, anon;
grant execute on function public.match_gym(double precision, double precision) to authenticated;

/* ---------------------------------------------------------- gyms_nearby -- */

create or replace function public.gyms_nearby(
  lat double precision,
  lng double precision,
  result_limit integer default 20
)
returns table (
  id bigint,
  chain text,
  name text,
  short_name text,
  address text,
  city text,
  latitude double precision,
  longitude double precision,
  image_url text,
  distance_m double precision,
  member_count integer,
  is_home_gym boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with viewer as (
    select auth.uid() as id
  ),
  home as (
    select private.home_gym_id_for((select id from viewer)) as gym_id
  )
  select
    gym.id,
    gym.chain,
    gym.name,
    gym.short_name,
    gym.address,
    gym.city,
    gym.latitude,
    gym.longitude,
    gym.image_url,
    2 * 6371000 * asin(sqrt(
      power(sin(radians(gym.latitude - lat) / 2), 2)
      + cos(radians(lat)) * cos(radians(gym.latitude))
        * power(sin(radians(gym.longitude - lng) / 2), 2)
    )) as distance_m,
    private.gym_member_count(gym.id) as member_count,
    gym.id = (select gym_id from home) as is_home_gym
  from public.gym gym
  where gym.is_public
    and (select id from viewer) is not null
  order by distance_m asc
  limit least(greatest(coalesce(result_limit, 20), 1), 100);
$$;

revoke all on function public.gyms_nearby(double precision, double precision, integer) from public, anon;
grant execute on function public.gyms_nearby(double precision, double precision, integer) to authenticated;

/* ------------------------------------------------------ the user's gyms -- */

create or replace function public.my_home_gym()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.gym_summary(private.home_gym_id_for(auth.uid()), auth.uid());
$$;

revoke all on function public.my_home_gym() from public, anon;
grant execute on function public.my_home_gym() to authenticated;

-- Centres the viewer has trained in over the last 90 days, most often first.
create or replace function public.my_gyms()
returns table (
  id bigint,
  chain text,
  name text,
  short_name text,
  city text,
  image_url text,
  workout_count integer,
  is_home_gym boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with viewer as (
    select auth.uid() as id
  ),
  counts as (
    select workout.gym_id, count(*)::integer as workout_count
    from public.workout_type_instance workout
    where workout.user_id = (select id from viewer)
      and workout.gym_id is not null
      and workout.done = true
      and workout.deleted_at is null
      and workout.date::date >= current_date - 90
    group by workout.gym_id
  )
  select
    gym.id,
    gym.chain,
    gym.name,
    gym.short_name,
    gym.city,
    gym.image_url,
    counts.workout_count,
    gym.id = private.home_gym_id_for((select id from viewer)) as is_home_gym
  from counts
  join public.gym gym on gym.id = counts.gym_id
  where (select id from viewer) is not null
  order by counts.workout_count desc, gym.short_name asc;
$$;

revoke all on function public.my_gyms() from public, anon;
grant execute on function public.my_gyms() to authenticated;

/* ---------------------------------------------- ranked lifts, one query -- */

-- The one place the ranking rules live. Every leaderboard function selects
-- from this. Rows the viewer must not see (blocked either way, rejected and
-- not their own) are already gone; rank is computed over what remains, and a
-- rejected row of the viewer's own comes back with a null rank so the screen
-- can still show it to them.
--
--   target_gym_id  null for the whole country, which also forces verified only
--   scope          'gym' or 'friends' (people the viewer follows, plus the viewer)
--   unit           'kg' or 'bw' (weight over bodyweight; rows without one drop)
create or replace function private.ranked_lifts(
  viewer_id uuid,
  target_gym_id bigint,
  target_exercise_id bigint,
  scope text,
  unit text
)
returns table (
  lift_id bigint,
  rank bigint,
  user_id uuid,
  display_name text,
  avatar_path text,
  gym_id bigint,
  gym_short_name text,
  gym_city text,
  exercise_id bigint,
  exercise_name text,
  weight_kg numeric,
  reps integer,
  bodyweight_kg numeric,
  ratio numeric,
  sort_key numeric,
  video_status text,
  approvals integer,
  rejections integer,
  performed_at timestamptz,
  previous_weight_kg numeric,
  is_me boolean,
  row_json jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  with visible as (
    select
      lift.*,
      profile.display_name,
      profile.avatar_path,
      gym.short_name as gym_short_name,
      gym.city as gym_city,
      case
        when lift.bodyweight_kg is not null and lift.bodyweight_kg > 0
          then round(lift.weight_kg / lift.bodyweight_kg, 3)
        else null
      end as ratio
    from public.gym_lift lift
    join public.profiles profile on profile.id = lift.user_id
    join public.gym gym on gym.id = lift.gym_id
    where (target_gym_id is null or lift.gym_id = target_gym_id)
      and (target_exercise_id is null or lift.exercise_id = target_exercise_id)
      and gym.is_public
      and (
        lift.user_id = viewer_id
        or (
          lift.video_status <> 'rejected'
          and not private.blocked_between(viewer_id, lift.user_id)
        )
      )
      and (target_gym_id is not null or lift.video_status = 'verified')
      and (
        coalesce(scope, 'gym') <> 'friends'
        or lift.user_id = viewer_id
        or exists (
          select 1
          from public.user_follows follow
          where follow.follower_id = viewer_id
            and follow.following_id = lift.user_id
        )
      )
      and (coalesce(unit, 'kg') <> 'bw' or lift.bodyweight_kg is not null)
  ),
  ranked as (
    select
      visible.*,
      case when coalesce(unit, 'kg') = 'bw' then visible.ratio else visible.weight_kg end as sort_key,
      case
        when visible.video_status = 'rejected' then null
        else rank() over (
          partition by visible.exercise_id
          order by
            case when visible.video_status = 'rejected' then 1 else 0 end,
            case when coalesce(unit, 'kg') = 'bw' then visible.ratio else visible.weight_kg end desc,
            visible.performed_at asc,
            visible.id asc
        )
      end as rank
    from visible
  )
  select
    ranked.id,
    ranked.rank,
    ranked.user_id,
    ranked.display_name,
    ranked.avatar_path,
    ranked.gym_id,
    ranked.gym_short_name,
    ranked.gym_city,
    ranked.exercise_id,
    ranked.exercise_name,
    ranked.weight_kg,
    ranked.reps,
    ranked.bodyweight_kg,
    ranked.ratio,
    ranked.sort_key,
    ranked.video_status,
    ranked.approvals,
    ranked.rejections,
    ranked.performed_at,
    ranked.previous_weight_kg,
    ranked.user_id = viewer_id as is_me,
    -- The row as the client receives it. Built here, once, so every function
    -- below hands out the same shape.
    jsonb_build_object(
      'lift_id', ranked.id,
      'rank', ranked.rank,
      'user_id', ranked.user_id,
      'display_name', ranked.display_name,
      'avatar_path', ranked.avatar_path,
      'gym', jsonb_build_object('id', ranked.gym_id, 'short_name', ranked.gym_short_name, 'city', ranked.gym_city),
      'exercise_id', ranked.exercise_id,
      'exercise_name', ranked.exercise_name,
      'weight_kg', ranked.weight_kg,
      'reps', ranked.reps,
      'bodyweight_kg', ranked.bodyweight_kg,
      'ratio', ranked.ratio,
      'video_status', ranked.video_status,
      'approvals', ranked.approvals,
      'rejections', ranked.rejections,
      'performed_at', ranked.performed_at,
      'previous_weight_kg', ranked.previous_weight_kg,
      'is_me', ranked.user_id = viewer_id
    ) as row_json
  from ranked;
$$;

/* ------------------------------------------- gym_leaderboard_overview -- */

create or replace function public.gym_leaderboard_overview(
  target_gym_id bigint,
  scope text default 'gym',
  more_limit integer default 8
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := auth.uid();
  gym_json jsonb;
  featured_json jsonb;
  more_json jsonb;
  more_total integer;
begin
  if viewer_id is null then
    return null;
  end if;

  gym_json := private.gym_summary(target_gym_id, viewer_id);

  if gym_json is null then
    return null;
  end if;

  with ranked as (
    select * from private.ranked_lifts(viewer_id, target_gym_id, null, scope, 'kg')
  ),
  featured as (
    select
      fe.exercise_id,
      fe.exercise_name,
      fe.sort_order,
      (select count(*) from ranked r where r.exercise_id = fe.exercise_id and r.rank is not null) as lifter_count,
      (select r.row_json from ranked r where r.exercise_id = fe.exercise_id and r.rank = 1 order by r.performed_at asc, r.lift_id asc limit 1) as top,
      (select r.row_json from ranked r where r.exercise_id = fe.exercise_id and r.is_me limit 1) as me
    from private.featured_exercises() fe
  )
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'exercise_id', featured.exercise_id,
      'exercise_name', featured.exercise_name,
      'lifter_count', featured.lifter_count,
      'top', featured.top,
      'me', case
        when featured.me is null then null
        else featured.me || jsonb_build_object(
          'gap_to_top',
          case
            when featured.top is null then null
            else (featured.top ->> 'weight_kg')::numeric - (featured.me ->> 'weight_kg')::numeric
          end
        )
      end
    )
    order by featured.sort_order
  ), '[]'::jsonb)
  into featured_json
  from featured;

  with ranked as (
    select * from private.ranked_lifts(viewer_id, target_gym_id, null, scope, 'kg')
  ),
  others as (
    select
      r.exercise_id,
      max(r.exercise_name) as exercise_name,
      count(*) filter (where r.rank is not null) as lifter_count,
      (array_agg(r.display_name order by r.rank asc nulls last, r.performed_at asc))[1] as top_name,
      (array_agg(r.weight_kg order by r.rank asc nulls last, r.performed_at asc))[1] as top_weight_kg,
      max(r.rank) filter (where r.is_me) as my_rank
    from ranked r
    where r.exercise_id not in (select fe.exercise_id from private.featured_exercises() fe)
    group by r.exercise_id
  ),
  numbered as (
    select others.*, row_number() over (order by others.lifter_count desc, others.exercise_name asc) as row_number
    from others
  )
  select
    count(*)::integer,
    coalesce(jsonb_agg(
      jsonb_build_object(
        'exercise_id', numbered.exercise_id,
        'exercise_name', numbered.exercise_name,
        'lifter_count', numbered.lifter_count,
        'top_name', numbered.top_name,
        'top_weight_kg', numbered.top_weight_kg,
        'my_rank', numbered.my_rank
      )
      order by numbered.row_number
    ) filter (where more_limit is null or numbered.row_number <= more_limit), '[]'::jsonb)
  into more_total, more_json
  from numbered;

  return jsonb_build_object(
    'gym', gym_json,
    'scope', coalesce(scope, 'gym'),
    'featured', featured_json,
    'more', more_json,
    'more_total', more_total
  );
end;
$$;

revoke all on function public.gym_leaderboard_overview(bigint, text, integer) from public, anon;
grant execute on function public.gym_leaderboard_overview(bigint, text, integer) to authenticated;

/* ------------------------------------------- gym_exercise_leaderboard -- */

-- One page of a ranked list plus the viewer's own row. The cursor is the last
-- row's (sort_key, performed_at, lift_id); pass them back to get the next page.
-- With target_gym_id null it is the whole country, verified lifts only.
create or replace function public.gym_exercise_leaderboard(
  target_gym_id bigint,
  target_exercise_id bigint,
  scope text default 'gym',
  unit text default 'kg',
  page_limit integer default 50,
  cursor_sort_key numeric default null,
  cursor_performed_at timestamptz default null,
  cursor_id bigint default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := auth.uid();
  safe_limit integer := least(greatest(coalesce(page_limit, 50), 1), 100);
  rows_json jsonb;
  me_json jsonb;
  total_count integer;
  exercise_json jsonb;
  last_sort_key numeric;
  last_performed_at timestamptz;
  last_lift_id bigint;
  next_cursor jsonb := null;
begin
  if viewer_id is null then
    return null;
  end if;

  select jsonb_build_object('id', exercise.id, 'name', exercise.name)
  into exercise_json
  from public."Exercise" exercise
  where exercise.id = target_exercise_id;

  with ranked as (
    select * from private.ranked_lifts(viewer_id, target_gym_id, target_exercise_id, scope, unit)
  ),
  page as (
    select r.*
    from ranked r
    where r.rank is not null
      and (
        cursor_sort_key is null
        or r.sort_key < cursor_sort_key
        or (r.sort_key = cursor_sort_key and r.performed_at > cursor_performed_at)
        or (r.sort_key = cursor_sort_key and r.performed_at = cursor_performed_at and r.lift_id > cursor_id)
      )
    order by r.sort_key desc, r.performed_at asc, r.lift_id asc
    limit safe_limit
  )
  select
    (select count(*)::integer from ranked r where r.rank is not null),
    (select r.row_json from ranked r where r.is_me limit 1),
    coalesce((select jsonb_agg(page.row_json order by page.sort_key desc, page.performed_at asc, page.lift_id asc) from page), '[]'::jsonb),
    (select page.sort_key from page order by page.sort_key asc, page.performed_at desc, page.lift_id desc limit 1),
    (select page.performed_at from page order by page.sort_key asc, page.performed_at desc, page.lift_id desc limit 1),
    (select page.lift_id from page order by page.sort_key asc, page.performed_at desc, page.lift_id desc limit 1)
  into total_count, me_json, rows_json, last_sort_key, last_performed_at, last_lift_id;

  if jsonb_array_length(rows_json) = safe_limit then
    next_cursor := jsonb_build_object(
      'sort_key', last_sort_key,
      'performed_at', last_performed_at,
      'lift_id', last_lift_id
    );
  end if;

  return jsonb_build_object(
    'gym', case when target_gym_id is null then null else private.gym_summary(target_gym_id, viewer_id) end,
    'exercise', exercise_json,
    'scope', coalesce(scope, 'gym'),
    'unit', coalesce(unit, 'kg'),
    'total', total_count,
    'rows', rows_json,
    'me', me_json,
    'next_cursor', next_cursor
  );
end;
$$;

revoke all on function public.gym_exercise_leaderboard(bigint, bigint, text, text, integer, numeric, timestamptz, bigint) from public, anon;
grant execute on function public.gym_exercise_leaderboard(bigint, bigint, text, text, integer, numeric, timestamptz, bigint) to authenticated;

/* -------------------------------------- national_exercise_leaderboard -- */

create or replace function public.national_exercise_leaderboard(
  target_exercise_id bigint,
  unit text default 'kg',
  page_limit integer default 50,
  cursor_sort_key numeric default null,
  cursor_performed_at timestamptz default null,
  cursor_id bigint default null
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select public.gym_exercise_leaderboard(
    null, target_exercise_id, 'gym', unit, page_limit, cursor_sort_key, cursor_performed_at, cursor_id
  );
$$;

revoke all on function public.national_exercise_leaderboard(bigint, text, integer, numeric, timestamptz, bigint) from public, anon;
grant execute on function public.national_exercise_leaderboard(bigint, text, integer, numeric, timestamptz, bigint) to authenticated;

/* ---------------------------------------------------- national_strongest -- */

-- Top verified lift per featured exercise across every centre, for the card
-- on the Centres screen.
create or replace function public.national_strongest()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with viewer as (
    select auth.uid() as id
  ),
  home as (
    select private.home_gym_id_for((select id from viewer)) as gym_id
  ),
  ranked as (
    select * from private.ranked_lifts((select id from viewer), null, null, 'gym', 'kg')
  )
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'exercise_id', fe.exercise_id,
      'exercise_name', fe.exercise_name,
      'top', (
        select r.row_json || jsonb_build_object('is_home_gym', r.gym_id = (select gym_id from home))
        from ranked r
        where r.exercise_id = fe.exercise_id and r.rank = 1
        order by r.performed_at asc, r.lift_id asc
        limit 1
      )
    )
    order by fe.sort_order
  ), '[]'::jsonb)
  from private.featured_exercises() fe
  where (select id from viewer) is not null;
$$;

revoke all on function public.national_strongest() from public, anon;
grant execute on function public.national_strongest() to authenticated;

/* ------------------------------------------ gym_lift_verification_queue -- */

-- Lifts waiting for a video verdict in a centre, minus the viewer's own, minus
-- the ones they already voted on, minus anyone blocked. Oldest video first, so
-- a lift does not sit unreviewed because newer ones keep arriving.
create or replace function public.gym_lift_verification_queue(target_gym_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with viewer as (
    select auth.uid() as id
  ),
  ranked as (
    select * from private.ranked_lifts((select id from viewer), target_gym_id, null, 'gym', 'kg')
  ),
  pending as (
    select
      r.row_json,
      lift.video_path,
      lift.updated_at as video_uploaded_at,
      (
        select count(*) + 1
        from ranked other
        where other.exercise_id = r.exercise_id
          and other.rank is not null
          and other.video_status = 'verified'
          and other.weight_kg > r.weight_kg
      ) as rank_if_verified
    from ranked r
    join public.gym_lift lift on lift.id = r.lift_id
    where r.video_status = 'pending'
      and not r.is_me
      and lift.video_path is not null
      and not exists (
        select 1
        from public.gym_lift_vote vote
        where vote.lift_id = r.lift_id
          and vote.voter_id = (select id from viewer)
      )
  )
  select coalesce(jsonb_agg(
    pending.row_json || jsonb_build_object(
      'video_path', pending.video_path,
      'video_uploaded_at', pending.video_uploaded_at,
      'rank_if_verified', pending.rank_if_verified,
      'can_vote', private.trains_at_gym((select id from viewer), target_gym_id)
    )
    order by pending.video_uploaded_at asc
  ), '[]'::jsonb)
  from pending
  where (select id from viewer) is not null;
$$;

revoke all on function public.gym_lift_verification_queue(bigint) from public, anon;
grant execute on function public.gym_lift_verification_queue(bigint) to authenticated;

/* -------------------------------------------- request_lift_verification -- */

-- Tells up to ten recently active members of the centre that a lift is waiting
-- for their verdict, through the in-app inbox. Push delivery would need an
-- Edge Function like send-workout-started-notification; the inbox row is the
-- part the database can do on its own, and it is what the bell shows.
create or replace function public.request_lift_verification(target_lift_id bigint)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := auth.uid();
  lift public.gym_lift%rowtype;
  lifter_name text;
  gym_short_name text;
  event_id uuid;
  recipient_count integer := 0;
begin
  if viewer_id is null then
    raise exception 'You need to be signed in.' using errcode = '42501';
  end if;

  select * into lift from public.gym_lift where id = target_lift_id;

  if not found or lift.user_id <> viewer_id then
    raise exception 'That lift is not yours to send for verification.' using errcode = '42501';
  end if;

  if lift.video_path is null then
    raise exception 'Attach a video first.' using errcode = '23514';
  end if;

  select profile.display_name into lifter_name from public.profiles profile where profile.id = viewer_id;
  select gym.short_name into gym_short_name from public.gym gym where gym.id = lift.gym_id;

  insert into public.notification_events (event_key, event_type, actor_id, source_table, source_id, status, payload)
  values (
    'lift-verification:' || lift.id || ':' || floor(extract(epoch from timezone('utc', now())))::bigint,
    'lift_verification_requested',
    viewer_id,
    'gym_lift',
    lift.id::text,
    'processing',
    jsonb_build_object('lift_id', lift.id, 'gym_id', lift.gym_id, 'exercise_id', lift.exercise_id)
  )
  returning id into event_id;

  with members as (
    select workout.user_id, max(workout.date) as last_date
    from public.workout_type_instance workout
    where workout.gym_id = lift.gym_id
      and workout.done = true
      and workout.deleted_at is null
      and workout.date::date >= current_date - 90
      and workout.user_id <> viewer_id
      and not private.blocked_between(viewer_id, workout.user_id)
    group by workout.user_id
    order by last_date desc
    limit 10
  ),
  inserted as (
    insert into public.notification_inbox (user_id, actor_id, event_id, event_type, title, body, data)
    select
      members.user_id,
      viewer_id,
      event_id,
      'lift_verification_requested',
      coalesce(lifter_name, 'Someone') || ' wants a lift verified',
      lift.exercise_name || ' · ' || trim(to_char(lift.weight_kg, 'FM9999990.##')) || ' kg at ' || coalesce(gym_short_name, 'your centre'),
      jsonb_build_object('lift_id', lift.id, 'gym_id', lift.gym_id, 'exercise_id', lift.exercise_id)
    from members
    on conflict (user_id, event_id) do nothing
    returning 1
  )
  select count(*)::integer into recipient_count from inserted;

  update public.notification_events
  set recipient_count = request_lift_verification.recipient_count,
      status = 'sent',
      sent_at = timezone('utc', now()),
      updated_at = timezone('utc', now())
  where id = event_id;

  return recipient_count;
end;
$$;

revoke all on function public.request_lift_verification(bigint) from public, anon;
grant execute on function public.request_lift_verification(bigint) to authenticated;

commit;
