-- Reporting and term filtering: the two halves of Apple guideline 1.2 that
-- blocking did not already cover.
--
-- Run after 20260905143000_user-blocks.sql.
--
-- Apple requires four things of an app with user-generated content: a way to
-- filter objectionable material before it is posted, a way to report it once it
-- is, the ability to block a user, and published contact information. Blocking
-- came with the migration above and the contact address is in the privacy
-- policy. This file is the other two.
--
-- Both live on the server for the same reason the block check does: a rule that
-- only runs in the app is a suggestion, because the same API is reachable with
-- the anon key and a HTTP client.

/* --------------------------------------------------------- the reports -- */

create table if not exists public.user_reports (
  report_id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_user_id uuid not null references public.profiles(id) on delete cascade,
  -- Null when the whole account is being reported rather than one post. The
  -- post is not a foreign key on purpose: deleting the post must not delete the
  -- evidence, and a report about something that has since been taken down is
  -- exactly the report worth keeping.
  reported_post_id bigint,
  reason text not null,
  note text not null default '',
  status text not null default 'open',
  created_at timestamptz not null default timezone('utc', now()),
  constraint no_self_report check (reporter_id <> reported_user_id),
  constraint user_reports_reason_known check (
    reason in ('spam', 'harassment', 'inappropriate', 'impersonation', 'other')
  ),
  constraint user_reports_status_known check (
    status in ('open', 'reviewed', 'actioned', 'dismissed')
  ),
  constraint user_reports_note_length check (char_length(note) <= 1000)
);

create index if not exists user_reports_open_idx
  on public.user_reports (created_at desc)
  where status = 'open';

create index if not exists user_reports_reported_user_idx
  on public.user_reports (reported_user_id);

alter table public.user_reports enable row level security;

grant select, insert on table public.user_reports to authenticated;

-- Only the reporter sees their own rows, and only ever their own. The reported
-- person must not be able to learn that they were reported, or by whom - that
-- is what stops a report from turning into the next round of the argument.
-- Handling them is done with the service role, outside the app.
drop policy if exists "Reporters can view their own reports" on public.user_reports;
create policy "Reporters can view their own reports"
on public.user_reports
for select
to authenticated
using ((select auth.uid()) = reporter_id);

drop policy if exists "Users can report from their own account" on public.user_reports;
create policy "Users can report from their own account"
on public.user_reports
for insert
to authenticated
with check (
  (select auth.uid()) = reporter_id
  and reporter_id <> reported_user_id
);

-- No update or delete policy at all. A report is a record; the reporter does
-- not get to withdraw it and nobody in the app gets to change its status.

/* ----------------------------------------------------- the term filter -- */

-- A table rather than a constant in the client, so a term can be added without
-- shipping an app release - which on iOS means waiting for review.
create table if not exists public.blocked_terms (
  term text primary key,
  -- Informational. The filter does not branch on it; it is here so whoever
  -- maintains the list can see why a term is on it.
  language text not null default 'und',
  added_at timestamptz not null default timezone('utc', now())
);

alter table public.blocked_terms enable row level security;

-- Deliberately no policy and no grant to authenticated. The list is readable
-- only by the security definer function below. Publishing it would hand every
-- user the exact set of strings to work around.
revoke all on table public.blocked_terms from authenticated;
revoke all on table public.blocked_terms from anon;

create or replace function private.contains_blocked_term(candidate text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  haystack text;
begin
  if candidate is null or candidate = '' then
    return false;
  end if;

  -- Lowercased once, and non-letters collapsed to single spaces, so "s p a m"
  -- and "s.p.a.m" do not walk past a list that only holds "spam". Padded with
  -- spaces so the whole-word match below works at both ends.
  haystack := ' ' || regexp_replace(lower(candidate), '[^a-z0-9æøå]+', ' ', 'g') || ' ';

  return exists (
    select 1
    from public.blocked_terms blocked
    -- Whole word, not substring. A substring match is how a filter ends up
    -- rejecting "Scunthorpe" and "assessment", and a filter that fires on
    -- ordinary words gets worked around rather than respected.
    where position(' ' || blocked.term || ' ' in haystack) > 0
  );
end;
$function$;

revoke all on function private.contains_blocked_term(text) from public;
revoke all on function private.contains_blocked_term(text) from anon;
revoke all on function private.contains_blocked_term(text) from authenticated;

/* ------------------------------------------------------- the two guards -- */

create or replace function private.reject_blocked_terms_in_post()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if private.contains_blocked_term(new.title)
     or private.contains_blocked_term(new.body) then
    -- Says nothing about which word matched. Naming it is a recipe for getting
    -- around the filter, and the user does not need to know to fix the post.
    raise exception 'This post cannot be published.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$function$;

drop trigger if exists on_social_post_term_check on public.social_post;
create trigger on_social_post_term_check
before insert or update of title, body on public.social_post
for each row execute function private.reject_blocked_terms_in_post();

create or replace function private.reject_blocked_terms_in_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if private.contains_blocked_term(new.display_name)
     or private.contains_blocked_term(new.bio) then
    raise exception 'This profile cannot be saved.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$function$;

drop trigger if exists on_profile_term_check on public.profiles;
create trigger on_profile_term_check
before insert or update of display_name, bio on public.profiles
for each row execute function private.reject_blocked_terms_in_profile();

/* ------------------------------------------------------------ the list -- */

-- A deliberately short starting list: unambiguous slurs and the sexual terms
-- that have no ordinary use in a training log, in English and Danish. It is
-- meant to be added to from the reports that come in, not to be exhaustive on
-- day one - an over-broad list rejects innocent posts, and that is a worse
-- failure here than letting one through to be reported.
--
-- Add more with:
--   insert into public.blocked_terms (term, language) values ('<term>', 'da')
--   on conflict (term) do nothing;
insert into public.blocked_terms (term, language) values
  ('fuck', 'en'),
  ('shit', 'en'),
  ('bitch', 'en'),
  ('cunt', 'en'),
  ('slut', 'en'),
  ('whore', 'en'),
  ('rape', 'en'),
  ('nigger', 'en'),
  ('faggot', 'en'),
  ('retard', 'en'),
  ('kraftedeme', 'da'),
  ('luder', 'da'),
  ('ludder', 'da'),
  ('fisse', 'da'),
  ('pikhoved', 'da'),
  ('bøsserøv', 'da'),
  ('perker', 'da'),
  ('voldtægt', 'da')
on conflict (term) do nothing;

-- Note on the English list: "slut" is an ordinary Danish word meaning "end" or
-- "finished", and a Danish user could reasonably type it in a workout note.
-- The whole-word match does not help there, because the word is the match. It
-- is on the list anyway because the app's interface is English and posts are
-- read by English-speaking followers; if it turns out to reject real posts,
-- take it off rather than leaving users unable to say their workout is over.
